const en = {
  navigation: "Navigation",
  dropdown: "Dropdown",
  dropdownHelp: "Good for 5 or fewer sub navigation links",
  mega: "Mega menu",
  megaHelp: "Good for more than 5 sub navigation links",
  editLinks: "Edit links",
  customize: "Customize",
  layoutColor: "Layout and color",
  layout: "Layout",
  scroll: "Header scroll settings",
  sticky: "Sticky header",
  reveal: "Reveal on scroll up",
  none: "No effects",
  colorStyle: "Color style",
  default: "Default",
  background: "Background",
  transparent: "Transparent",
  style: "Your selected color style",
  color: "Custom color",
  gradient: "Gradient",
  image: "Image",
  content: "Content",
  logo: "Logo",
  button: "Button",
  icons: "Icons",
  fulfillment: "Fulfillment and Scheduling",
  fulfillmentHelp:
    "Turning this feature off will remove it from all pages except for Order Online.",
  type: "Type",
  text: "Text",
  size: "Size",
  customBackground: "Custom background",
  logoHelp: "We automatically link your logo to your homepage",
  caps: "Menu links all CAPS",
  filled: "Filled",
  outline: "Outline",
  reset: "Reset to Default",
  cart: "Cart icon",
  search: "Search icon",
  link: "Links to",
  edit: "Edit",
  home: "Home",
  page: "Standard page",
  order: "Order Online",
  url: "External link",
  phone: "Phone link",
  email: "Email link",
  file: "File link",
  cancel: "Cancel",
  save: "Save",
  addLink: "Add navigation link",
  arrange: "Drag links to arrange",
  label: "Link label",
  target: "Link to",
  anchor: "Section",
  newTab: "Open in a new tab",
  parent: "Parent link",
  topLevel: "Top level",
  remove: "Remove",
  replace: "Replace",
  upload: "Add image",
  busy: "Uploading…",
  uploadError: "The image could not be uploaded. Please try again.",
  invalidLink: "Enter a valid destination.",
  back: "Back",
  tip: "Pro tip: Brand your header by adding an image to this layout",
  addBackground: "Add background image",
  overlay: "Overlay opacity",
  angle: "Angle",
  endColor: "End color",
  buttonText: "Button text",
  logoText: "Logo text",
  moveUp: "Move up",
  moveDown: "Move down",
  left: "Logo on the left, centered links",
  center: "Centered logo, links on the left",
  right: "Logo left, links right",
  stacked: "Centered logo with links below",
  compact: "Framed logo and links on the left",
  centered: "Framed centered logo, links on the left",
  textColor: "Text color",
  brandColor: "Use site colors",
  removeLink: "Remove link",
};
const fr: typeof en = {
  navigation: "Navigation",
  dropdown: "Menu déroulant",
  dropdownHelp: "Idéal pour 5 sous-liens de navigation ou moins",
  mega: "Méga menu",
  megaHelp: "Idéal pour plus de 5 sous-liens de navigation",
  editLinks: "Modifier les liens",
  customize: "Personnaliser",
  layoutColor: "Disposition et couleur",
  layout: "Disposition",
  scroll: "Défilement de l’en-tête",
  sticky: "En-tête fixe",
  reveal: "Révéler au défilement vers le haut",
  none: "Aucun effet",
  colorStyle: "Style de couleur",
  default: "Par défaut",
  background: "Arrière-plan",
  transparent: "Transparent",
  style: "Votre style de couleur sélectionné",
  color: "Couleur personnalisée",
  gradient: "Dégradé",
  image: "Image",
  content: "Contenu",
  logo: "Logo",
  button: "Bouton",
  icons: "Icônes",
  fulfillment: "Retrait, livraison et planification",
  fulfillmentHelp:
    "Désactiver cette fonctionnalité la retire de toutes les pages, sauf de la page de commande.",
  type: "Type",
  text: "Texte",
  size: "Taille",
  customBackground: "Arrière-plan personnalisé",
  logoHelp: "Votre logo est automatiquement lié à votre page d’accueil",
  caps: "Liens du menu en MAJUSCULES",
  filled: "Plein",
  outline: "Contour",
  reset: "Rétablir les valeurs par défaut",
  cart: "Icône du panier",
  search: "Icône de recherche",
  link: "Lien vers",
  edit: "Modifier",
  home: "Accueil",
  page: "Page standard",
  order: "Commander en ligne",
  url: "Lien externe",
  phone: "Lien téléphonique",
  email: "Lien e-mail",
  file: "Lien vers un fichier",
  cancel: "Annuler",
  save: "Enregistrer",
  addLink: "Ajouter un lien de navigation",
  arrange: "Faites glisser les liens pour les organiser",
  label: "Libellé du lien",
  target: "Lien vers",
  anchor: "Section",
  newTab: "Ouvrir dans un nouvel onglet",
  parent: "Lien parent",
  topLevel: "Premier niveau",
  remove: "Supprimer",
  replace: "Remplacer",
  upload: "Ajouter une image",
  busy: "Importation…",
  uploadError: "L’image n’a pas pu être importée. Réessayez.",
  invalidLink: "Saisissez une destination valide.",
  back: "Retour",
  tip: "Astuce : personnalisez votre en-tête en ajoutant une image à cette disposition",
  addBackground: "Ajouter une image d’arrière-plan",
  overlay: "Opacité de la superposition",
  angle: "Angle",
  endColor: "Couleur de fin",
  buttonText: "Texte du bouton",
  logoText: "Texte du logo",
  moveUp: "Monter",
  moveDown: "Descendre",
  left: "Logo à gauche, liens centrés",
  center: "Logo centré, liens à gauche",
  right: "Logo à gauche, liens à droite",
  stacked: "Logo centré, liens en dessous",
  compact: "Logo encadré et liens à gauche",
  centered: "Logo encadré centré, liens à gauche",
  textColor: "Couleur du texte",
  brandColor: "Utiliser les couleurs du site",
  removeLink: "Supprimer le lien",
};
const he: typeof en = {
  ...en,
  navigation: "ניווט",
  dropdown: "תפריט נפתח",
  dropdownHelp: "מתאים ל־5 קישורי משנה או פחות",
  mega: "תפריט מורחב",
  megaHelp: "מתאים ליותר מ־5 קישורי משנה",
  editLinks: "עריכת קישורים",
  customize: "התאמה אישית",
  layoutColor: "פריסה וצבע",
  layout: "פריסה",
  scroll: "גלילת כותרת",
  sticky: "כותרת דביקה",
  reveal: "הצגה בגלילה למעלה",
  none: "ללא אפקטים",
  colorStyle: "סגנון צבע",
  default: "ברירת מחדל",
  background: "רקע",
  transparent: "שקוף",
  style: "סגנון הצבע שנבחר",
  color: "צבע מותאם אישית",
  gradient: "מעבר צבעים",
  image: "תמונה",
  content: "תוכן",
  logo: "לוגו",
  button: "כפתור",
  icons: "סמלים",
  fulfillment: "איסוף, משלוח ותזמון",
  fulfillmentHelp: "השבתה תסיר את האפשרות מכל העמודים פרט לעמוד ההזמנה.",
  type: "סוג",
  text: "טקסט",
  size: "גודל",
  customBackground: "רקע מותאם אישית",
  logoHelp: "הלוגו מקושר אוטומטית לעמוד הבית",
  caps: "קישורי תפריט באותיות גדולות",
  filled: "מלא",
  outline: "מסגרת",
  reset: "איפוס לברירת מחדל",
  cart: "סמל סל קניות",
  search: "סמל חיפוש",
  link: "קישור אל",
  edit: "עריכה",
  home: "בית",
  page: "עמוד רגיל",
  order: "הזמנה אונליין",
  url: "קישור חיצוני",
  phone: "טלפון",
  email: "אימייל",
  file: "קובץ",
  cancel: "ביטול",
  save: "שמירה",
  addLink: "הוספת קישור ניווט",
  arrange: "גררו קישורים לסידור",
  label: "טקסט הקישור",
  target: "קישור אל",
  anchor: "מקטע",
  newTab: "פתיחה בלשונית חדשה",
  parent: "קישור אב",
  topLevel: "רמה ראשית",
  remove: "הסרה",
  replace: "החלפה",
  upload: "הוספת תמונה",
  busy: "מעלה…",
  uploadError: "העלאת התמונה נכשלה. נסו שוב.",
  invalidLink: "הזינו יעד תקין.",
  back: "חזרה",
  tip: "הוסיפו תמונת רקע כדי למתג את הכותרת",
  addBackground: "הוספת תמונת רקע",
  overlay: "אטימות שכבה",
  angle: "זווית",
  endColor: "צבע סיום",
  buttonText: "טקסט הכפתור",
  logoText: "טקסט הלוגו",
  moveUp: "הזזה למעלה",
  moveDown: "הזזה למטה",
  left: "לוגו משמאל וקישורים ממורכזים",
  center: "לוגו ממורכז וקישורים משמאל",
  right: "לוגו משמאל וקישורים מימין",
  stacked: "לוגו ממורכז וקישורים מתחת",
  compact: "לוגו ממוסגר וקישורים משמאל",
  centered: "לוגו ממוסגר במרכז וקישורים משמאל",
  textColor: "צבע טקסט",
  brandColor: "שימוש בצבעי האתר",
  removeLink: "הסרת קישור",
};
/** Localized copy for the Header component across all supported admin languages. */
export function headerCopy(locale: string) {
  return locale === "fr" ? fr : locale === "he" ? he : en;
}
export type HeaderCopy = typeof en;
