'use client';

import dynamic from 'next/dynamic';
import Link from 'next/link';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useParams } from 'next/navigation';
import { CircleAlert, MapPin, Trash2, Plus, RefreshCw, Map, Search } from 'lucide-react';
import { getDeliveryZones, createDeliveryZone, updateDeliveryZone, deleteDeliveryZone, getRestaurant, geocodeAddress, ApiError, type DeliveryZone, type DeliveryZoneInput } from '@/lib/api';
import { checkedDeliveryZones, deliveryZoneDraft, deliveryZoneDraftError, deliveryZonePayload, deliveryZoneSignature, deliveryZoneCanDraw, validZoneCoordinate, type DeliveryZoneDraft, type ZoneCoordinate } from '@/lib/delivery-zone-state';
import { lookupCityCoord } from '@/lib/israel-cities';
import { useI18n, useCurrency } from '@/lib/i18n';
import { usePermissions } from '@/lib/permissions-context';
import { useIsMobile } from '@/components/ui/use-mobile';
import { Button, ConfirmDialog, Drawer, EmptyState, Field, Input, PageHead, Section, Select } from '@/components/ds';
import { Checkbox } from '@/components/ui/checkbox';
import { DeliveryMinimum } from './DeliveryMinimum';

const ZoneMap = dynamic(() => import('@/components/delivery/ZoneMap'), { ssr: false });
const DEFAULT_CENTER = {lat:32.0853,lng:34.7818};
type PendingZoneAction = {kind:'save';id?:number;input:DeliveryZoneInput;before:number[]} | {kind:'delete';id:number};
type T = (key:string)=>string;

/** Keep delivery drafts scoped to the active restaurant. */
export default function DeliveryZonesPage(){const {restaurantId}=useParams();return <DeliveryZonesWorkspace key={String(restaurantId)} rid={Number(restaurantId)} />;}
function DeliveryZonesWorkspace({rid}:{rid:number}){
  const {t,locale}=useI18n(), {money}=useCurrency(), {hasAnyPermission}=usePermissions();
  const canManage=hasAnyPermission('orders.manage'), isMobile=useIsMobile();
  const [zones,setZones]=useState<DeliveryZone[]>([]),[loaded,setLoaded]=useState(false),[loading,setLoading]=useState(false),[loadError,setLoadError]=useState(false);
  const [center,setCenter]=useState<ZoneCoordinate|null>(null),[addressState,setAddressState]=useState<'loading'|'ready'|'missing'|'unavailable'>('loading'),[address,setAddress]=useState('');
  const [draft,setDraft]=useState<DeliveryZoneDraft|null>(null),[cityInput,setCityInput]=useState(''),[search,setSearch]=useState(''),[showMap,setShowMap]=useState(false);
  const [busy,setBusy]=useState(false),[pending,setPending]=useState<PendingZoneAction|null>(null),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null),[savedVersion,setSavedVersion]=useState<DeliveryZone|null>(null);
  const [confirmation,setConfirmation]=useState<{kind:'delete'|'disable';zone:DeliveryZone}|null>(null),[discard,setDiscard]=useState<'close'|'adopt'|null>(null);
  const alive=useRef(true),sequence=useRef(0),geoSequence=useRef(0),lock=useRef(false),baseline=useRef(''),original=useRef<DeliveryZone|undefined>();
  const nameRef=useRef<HTMLInputElement>(null),cityRef=useRef<HTMLInputElement>(null);
  const dirty=!!draft&&(JSON.stringify(draft)!==baseline.current||!!cityInput.trim()), frozen=busy||!!pending;
  useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
  useEffect(()=>{if(!dirty&&!frozen)return;const guard=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue='';};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[dirty,frozen]);
  useEffect(()=>{if(error||pending)requestAnimationFrame(()=>{const nodes=Array.from(document.querySelectorAll<HTMLElement>('[data-zone-feedback]'));nodes[nodes.length-1]?.focus();});},[error,pending,busy]);
  const load=useCallback(async()=>{if(!canManage||lock.current)return;const generation=++sequence.current;setLoading(true);setLoadError(false);try{const rows=checkedDeliveryZones(await getDeliveryZones(rid),rid).filter(row=>!row.tour_only);if(alive.current&&generation===sequence.current){setZones(rows);setLoaded(true);}}catch{if(alive.current&&generation===sequence.current)setLoadError(true);}finally{if(alive.current&&generation===sequence.current)setLoading(false);}},[rid,canManage]);
  const loadAddress=useCallback(async()=>{if(!canManage)return;const generation=++geoSequence.current;setAddressState('loading');try{const restaurant=await getRestaurant(rid);const name=restaurant.address?.trim()??'';if(!alive.current||generation!==geoSequence.current)return;setAddress(name);if(!name){setCenter(null);setAddressState('missing');return;}const geo=await geocodeAddress(rid,name);if(!alive.current||generation!==geoSequence.current)return;const position={lat:geo.lat!,lng:geo.lng!};if(geo.found&&validZoneCoordinate(position)){setCenter(position);setAddressState('ready');}else{setCenter(null);setAddressState(geo.unavailable||geo.found?'unavailable':'missing');}}catch{if(alive.current&&generation===geoSequence.current){setCenter(null);setAddressState('unavailable');}}},[rid,canManage]);
  useEffect(()=>{void load();void loadAddress();},[load,loadAddress]);
  const openDraft=(zone?:DeliveryZone)=>{if(!canManage||frozen||lock.current)return;const next=deliveryZoneDraft(zone,center);original.current=zone;baseline.current=JSON.stringify(next);setDraft(next);setCityInput('');setError(null);setNotice(null);setSavedVersion(null);};
  const close=()=>{if(frozen||lock.current)return;if(dirty||cityInput.trim())setDiscard('close');else{setDraft(null);setError(null);setSavedVersion(null);setCityInput('');}};
  const begin=()=>{if(!canManage||lock.current||pending)return false;lock.current=true;sequence.current++;setBusy(true);setError(null);setNotice(null);setSavedVersion(null);return true;};
  const finish=()=>{lock.current=false;if(alive.current)setBusy(false);};
  const accept=(zone:DeliveryZone)=>{setZones(rows=>zone.tour_only?rows.filter(row=>row.id!==zone.id):rows.some(row=>row.id===zone.id)?rows.map(row=>row.id===zone.id?zone:row):[...rows,zone]);setDraft(null);setCityInput('');setPending(null);setSavedVersion(null);setError(null);setNotice('deliveryZoneSaved');};
  const run=async(action:PendingZoneAction)=>{
    if(!begin())return;
    try{if(action.kind==='delete'){await deleteDeliveryZone(rid,action.id);if(alive.current){setZones(rows=>rows.filter(row=>row.id!==action.id));setNotice('deliveryZoneRemoved');setConfirmation(null);}}
    else{const saved=checkedDeliveryZones([action.id?await updateDeliveryZone(rid,action.id,action.input):await createDeliveryZone(rid,action.input)],rid)[0];if(action.id?saved.id!==action.id:action.before.includes(saved.id))throw new Error('Unexpected zone identity');if(alive.current)accept(saved);}}
    catch(reason){if(alive.current){setConfirmation(null);if(reason instanceof ApiError&&reason.status===409)setError('tourZoneInUse');else{setPending(action);setError('deliveryZoneUncertain');}}}
    finally{finish();}
  };
  const save=()=>{if(!draft||!dirty||frozen||!canManage)return;if(cityInput.trim()){setError('deliveryZoneCityUnadded');cityRef.current?.focus();return;}const problem=deliveryZoneDraftError(draft);if(problem){setError(problem);return;}void run({kind:'save',id:draft.id,input:deliveryZonePayload(draft,original.current),before:zones.map(row=>row.id)});};
  const toggle=(zone:DeliveryZone)=>{if(!canManage||frozen)return;if(zone.is_active&&zones.filter(row=>row.is_active).length===1){setConfirmation({kind:'disable',zone});return;}void run({kind:'save',id:zone.id,input:{name:zone.name,type:zone.type,is_active:!zone.is_active,polygon:zone.polygon,center_lat:zone.center_lat,center_lng:zone.center_lng,radius_m:zone.radius_m,cities:zone.cities,delivery_fee:zone.delivery_fee??null,min_order:zone.min_order??null},before:zones.map(row=>row.id)});};
  const verify=async()=>{
    if(!pending||lock.current)return;lock.current=true;setBusy(true);setError(null);const action=pending;
    try{const rows=checkedDeliveryZones(await getDeliveryZones(rid),rid);if(!alive.current)return;setZones(rows.filter(row=>!row.tour_only));setPending(null);
      if(action.kind==='delete'){setError(rows.some(row=>row.id===action.id)?'deliveryZoneStillPresent':null);if(!rows.some(row=>row.id===action.id))setNotice('deliveryZoneRemoved');}
      else{const matches=action.id?rows.filter(row=>row.id===action.id):rows.filter(row=>!action.before.includes(row.id)&&deliveryZoneSignature(row)===deliveryZoneSignature(action.input));const current=matches.length===1?matches[0]:null;if(current&&!current.tour_only&&deliveryZoneSignature(current)===deliveryZoneSignature(action.input))accept(current);else{setSavedVersion(current);setError(current?'deliveryZoneSavedDiffers':'deliveryZoneReviewAfterSave');}}
    }catch{if(alive.current)setError('deliveryZoneReadbackError');}finally{finish();}
  };
  const addCity=()=>{if(!draft||frozen)return;const next=cityInput.trim();if(!next)return;if(draft.cities.some(city=>city.trim().toLocaleLowerCase(locale)===next.toLocaleLowerCase(locale))){setError('deliveryZoneCityDuplicate');return;}setDraft({...draft,cities:[...draft.cities,next]});setCityInput('');setError(null);cityRef.current?.focus();};
  const visible=useMemo(()=>{const query=search.trim().toLocaleLowerCase(locale);return zones.filter(zone=>!query||`${zone.name} ${(zone.cities??[]).join(' ')}`.toLocaleLowerCase(locale).includes(query));},[zones,search,locale]);
  const mapCenter=center??zones.map(zone=>({lat:zone.center_lat!,lng:zone.center_lng!})).find(validZoneCoordinate)??DEFAULT_CENTER;
  const cityMarkers=draft?.type==='cities'?draft.cities.flatMap(name=>{const coord=lookupCityCoord(name);return coord?[{name,lat:coord.lat,lng:coord.lng}]:[];}):[];
  const feedback=<>{notice&&<ZoneFeedback text={t(notice)} />}{(error||pending)&&<div tabIndex={-1} data-zone-feedback className="space-y-3 rounded-r-lg border border-[var(--danger-500)] p-4 focus:outline-none"><ZoneFeedback error text={t(error??'deliveryZoneUncertain')} />{pending&&<Button variant="secondary" size="sm" disabled={busy} onClick={()=>void verify()}>{t('deliveryVerifySaved')}</Button>}{savedVersion&&<><p className="font-semibold" dir="auto">{savedVersion.name}</p><ZoneDetails zone={savedVersion} t={t} money={money} /><p className="text-fs-xs">{savedVersion.center_lat!=null&&savedVersion.center_lng!=null&&<bdi>{savedVersion.center_lat}, {savedVersion.center_lng}</bdi>}</p>{deliveryZoneCanDraw(savedVersion)&&<ZoneMap className="h-[180px] overflow-hidden rounded-r-md" center={validZoneCoordinate({lat:savedVersion.center_lat!,lng:savedVersion.center_lng!})?{lat:savedVersion.center_lat!,lng:savedVersion.center_lng!}:mapCenter} restaurantCenter={center} zones={[savedVersion]} draftPolygon={[]} drawMode="none" onMapClick={()=>{}} interactive={false} />}{!!savedVersion.polygon?.length&&<p className="text-fs-xs">{t('deliveryZonePolygonPoints').replace('{n}',String(savedVersion.polygon.length))}</p>}{draft&&!savedVersion.tour_only&&<Button variant="secondary" size="sm" disabled={frozen} onClick={()=>setDiscard('adopt')}>{t('deliveryUseSaved')}</Button>}</>}</div>}</>;
  return <div className="mx-auto max-w-[1240px] space-y-6 pb-8"><PageHead title={t('deliveryZones')} desc={t('deliveryZoneWorkspaceDesc')} actions={canManage?<Button variant="primary" size="md" disabled={!loaded||frozen} onClick={()=>openDraft()}><Plus />{t('addZone')}</Button>:undefined} /><DeliveryMinimum rid={rid} />{!canManage?<Section><ZoneFeedback text={t('deliveryZonePermissionHint')} /></Section>:<>
    {!draft&&feedback}{loadError&&<Section><ZoneFeedback error text={t('deliveryZoneLoadError')} /><Button variant="secondary" size="sm" disabled={loading||frozen} className="mt-3" onClick={()=>void load()}>{t('retry')}</Button></Section>}{!loaded&&loading&&<p role="status" className="flex items-center gap-3 py-8"><RefreshCw className="size-5 animate-spin" />{t('loading')}</p>}{loaded&&<>
    <div className="rounded-r-xl bg-[var(--summary-bg)] p-5 text-[var(--summary-fg)]"><p className="flex items-center gap-3 font-semibold"><MapPin className="size-5" />{t('deliveryZoneCoverageTitle')}</p><p className="mt-2 text-fs-sm leading-relaxed">{t(zones.some(zone=>zone.is_active)?'deliveryZoneActiveCoverage':'deliveryZoneNoActiveCoverage')}</p></div><div className="flex items-end gap-3"><Field label={t('deliveryZoneSearch')} grow><Input type="search" value={search} onChange={event=>setSearch(event.target.value)} /></Field><Button variant="secondary" size="md" icon aria-label={t('refresh')} disabled={loading||frozen} onClick={()=>void load()}><RefreshCw className={loading?'animate-spin':''} /></Button>{isMobile&&<Button variant="secondary" size="md" icon aria-label={t('deliveryZoneShowMap')} aria-expanded={showMap} onClick={()=>setShowMap(value=>!value)}><Map /></Button>}</div>
    <div className="grid items-start gap-6 lg:grid-cols-[minmax(0,1fr)_400px]">
      <div className="space-y-3">{visible.map(zone=><article key={zone.id} className="rounded-r-xl border border-[var(--line)] bg-[var(--surface)] p-4 sm:p-5"><div className="flex items-start gap-3"><button disabled={frozen} className="min-w-0 flex-1 text-start text-fs-md font-semibold text-[var(--brand-ink)] underline underline-offset-4 [overflow-wrap:anywhere]" dir="auto" onClick={()=>openDraft(zone)}>{zone.name}</button><Button variant="ghost" size="sm" icon disabled={frozen} aria-label={`${t('remove')} · ${zone.name}`} onClick={()=>setConfirmation({kind:'delete',zone})}><Trash2 className="text-[var(--danger-500)]" /></Button></div><div className="mt-4"><ZoneDetails zone={zone} t={t} money={money} /></div><label className="mt-4 flex items-center gap-3 text-fs-sm"><Checkbox checked={zone.is_active} disabled={frozen} onCheckedChange={()=>toggle(zone)} aria-label={`${t('deliveryZoneEnabled')} · ${zone.name}`} /><span>{t('deliveryZoneEnabled')}</span></label></article>)}{!visible.length&&<Section><EmptyState icon={<Search />} title={t(zones.length?'deliveryZoneNoMatches':'deliveryZoneEmpty')} action={zones.length?<Button variant="secondary" size="sm" onClick={()=>setSearch('')}>{t('reset')}</Button>:undefined} /></Section>}</div>
      {(!isMobile||showMap)&&<section aria-label={t('deliveryZoneMapTitle')} className="space-y-3"><ZoneMap className="h-[260px] overflow-hidden rounded-r-xl border border-[var(--line)] lg:h-[440px]" center={mapCenter} restaurantCenter={center} zones={zones.filter(deliveryZoneCanDraw)} drawMode="none" draftPolygon={[]} onMapClick={()=>{}} interactive={!isMobile} /><p className="text-fs-xs text-[var(--fg-muted)]">{t(center?'deliveryZoneMapHint':'deliveryZoneMapNoOrigin')}</p></section>}
    </div></>}
  </>}
  <Drawer open={!!draft} onOpenChange={open=>{if(!open)close();}} title={t(draft?.id?'deliveryZoneEdit':'addZone')} width={660} initialFocusRef={nameRef} closeDisabled={frozen} onSave={save} saveLabel={t(busy?'saving':'save')} saveDisabled={frozen||!dirty||!canManage}>
    {draft&&<div className="space-y-6">{feedback}{!draft.isActive&&!zones.some(zone=>zone.id!==draft.id&&zone.is_active)&&<ZoneFeedback text={t('deliveryZoneNoActiveCoverage')} />}<fieldset disabled={frozen||!canManage} className="min-w-0 space-y-5"><Field label={t('zoneName')} grow><Input ref={nameRef} value={draft.name} dir="auto" onChange={event=>setDraft({...draft,name:event.target.value})} /></Field><Field label={t('deliveryZoneType')} grow><Select value={draft.type} onChange={event=>setDraft({...draft,type:event.target.value as DeliveryZoneDraft['type']})}>{original.current?.type==='polygon'&&<option value="polygon">{t('zoneType_polygon')}</option>}<option value="radius">{t('zoneType_radius')}</option><option value="cities">{t('zoneType_cities')}</option></Select></Field>
    {draft.type==='radius'&&<section className="space-y-4 rounded-r-xl border border-[var(--line)] p-4"><p className="text-fs-sm">{t(draft.id?'deliveryZoneStoredOrigin':'radiusFromAddressHint')}</p>{validZoneCoordinate(draft.center)&&<p className="text-fs-xs text-[var(--fg-muted)]"><bdi>{draft.center.lat}, {draft.center.lng}</bdi></p>}{addressState==='loading'?<p role="status" className="text-fs-sm">{t('deliveryZoneLocating')}</p>:addressState==='ready'?<><p className="text-fs-xs text-[var(--fg-muted)]" dir="auto">{address}</p>{JSON.stringify(draft.center)!==JSON.stringify(center)&&<Button variant="secondary" size="sm" className="h-auto max-w-full whitespace-normal text-start" onClick={()=>setDraft({...draft,center})}>{t('deliveryZoneUseRestaurantOrigin')}</Button>}</>:<div className="space-y-3"><ZoneFeedback text={t(addressState==='unavailable'?'deliveryZoneGeocodeUnavailable':'radiusMissingAddress')} />{addressState==='unavailable'&&<Button variant="secondary" size="sm" onClick={()=>void loadAddress()}>{t('retry')}</Button>}<Link className="text-fs-sm text-[var(--brand-ink)] underline" href={`/${rid}/settings`}>{t('generalSettings')}</Link></div>}<Field label={t('radiusKm')} grow><Input type="text" inputMode="decimal" value={draft.radiusKm} dir="ltr" onChange={event=>setDraft({...draft,radiusKm:event.target.value})} /></Field></section>}
    {draft.type==='cities'&&<section className="space-y-4"><p className="text-fs-sm text-[var(--fg-muted)]">{t('zoneTypeHint_cities')}</p><div className="flex items-end gap-3"><Field label={t('cityOrPostal')} grow><Input ref={cityRef} value={cityInput} dir="auto" onChange={event=>setCityInput(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'){event.preventDefault();addCity();}}} /></Field><Button variant="secondary" size="md" onClick={addCity} disabled={!cityInput.trim()}>{t('add')}</Button></div><div className="flex flex-wrap gap-2">{draft.cities.map((city,index)=><div key={`${city}-${index}`} className="flex max-w-full items-center gap-2 rounded-r-md border border-[var(--line)] bg-[var(--surface)] ps-3"><span className="text-fs-sm [overflow-wrap:anywhere]" dir="auto">{city}</span><Button variant="ghost" size="sm" icon aria-label={`${t('remove')} · ${city}`} onClick={()=>setDraft({...draft,cities:draft.cities.filter((_,i)=>i!==index)})}><Trash2 /></Button></div>)}</div></section>}
    {draft.type==='polygon'&&<ZoneFeedback text={t('deliveryZonePolygonLegacy').replace('{n}',String(draft.polygon.length))} />}
    {(draft.type==='cities'||draft.type==='polygon'&&draft.polygon.length>=3&&draft.polygon.every(([lng,lat])=>validZoneCoordinate({lat,lng}))||draft.type==='radius'&&validZoneCoordinate(draft.center)&&Number(draft.radiusKm)>0&&Number.isFinite(Number(draft.radiusKm)))&&<ZoneMap className="h-[190px] overflow-hidden rounded-r-xl border border-[var(--line)]" center={draft.center&&validZoneCoordinate(draft.center)?draft.center:mapCenter} restaurantCenter={center} zones={[]} draftCenter={draft.type==='radius'?draft.center:null} draftRadiusM={Math.round(Number(draft.radiusKm)*1000)} draftPolygon={draft.type==='polygon'?draft.polygon:[]} cityMarkers={cityMarkers} drawMode="none" onMapClick={()=>{}} interactive={false} />}
    <div className="grid gap-4 min-[420px]:grid-cols-2"><Field label={t('zoneDeliveryFee')} grow><Input type="text" inputMode="decimal" dir="ltr" value={draft.deliveryFee} placeholder={t('zoneFeeFreePlaceholder')} onChange={event=>setDraft({...draft,deliveryFee:event.target.value})} /></Field><Field label={t('zoneMinOrder')} grow><Input type="text" inputMode="decimal" dir="ltr" value={draft.minOrder} placeholder={t('zoneMinGlobalPlaceholder')} onChange={event=>setDraft({...draft,minOrder:event.target.value})} /></Field></div><p className="text-fs-xs text-[var(--fg-muted)]">{t('zoneFeeMinHint')}</p><label className="flex items-center gap-3 text-fs-sm"><Checkbox checked={draft.isActive} onCheckedChange={checked=>setDraft({...draft,isActive:checked===true})} /><span>{t('deliveryZoneEnabled')}</span></label></fieldset></div>}
  </Drawer>
  <ConfirmDialog open={!!confirmation} onOpenChange={open=>{if(!open&&!lock.current)setConfirmation(null);}} title={t(confirmation?.kind==='disable'?'deliveryZoneDisableTitle':'deliveryZoneDeleteTitle')} description={<><strong dir="auto">{confirmation?.zone.name}</strong><span className="mt-2 block">{t(confirmation?.zone.is_active&&zones.filter(zone=>zone.is_active).length===1?'deliveryZoneNoActiveCoverage':'deliveryZoneDeleteHint')}</span></>} confirmLabel={t(confirmation?.kind==='disable'?'deliveryZoneDisable':'remove')} cancelLabel={t('cancel')} danger onConfirm={()=>{if(!confirmation)return;const {kind,zone}=confirmation;if(kind==='delete')void run({kind:'delete',id:zone.id});else{setConfirmation(null);void run({kind:'save',id:zone.id,input:{name:zone.name,type:zone.type,is_active:false,polygon:zone.polygon,center_lat:zone.center_lat,center_lng:zone.center_lng,radius_m:zone.radius_m,cities:zone.cities,delivery_fee:zone.delivery_fee??null,min_order:zone.min_order??null},before:zones.map(row=>row.id)});}}} />
  <ConfirmDialog open={!!discard} onOpenChange={open=>{if(!open)setDiscard(null);}} title={t('discardUnsavedChanges')} description={t('discountDiscardHint')} confirmLabel={t(discard==='adopt'?'deliveryUseSaved':'discardChanges')} cancelLabel={t('cancel')} onConfirm={()=>{if(frozen)return;const action=discard;setDiscard(null);if(action==='adopt'&&savedVersion)openDraft(savedVersion);else{setDraft(null);setCityInput('');setError(null);setSavedVersion(null);}}} />
  </div>;
}
function ZoneDetails({zone,t,money}:{zone:DeliveryZone;t:T;money:(value:number)=>string}){return <div className="space-y-2 text-fs-sm"><p className="text-[var(--fg-muted)]">{t(zone.is_active?'active':'inactive')} · {t(`zoneType_${zone.type}`)}{zone.type==='radius'&&zone.radius_m!=null&&<> · <bdi>{zone.radius_m/1000} {t('deliveryZoneKilometers')}</bdi></>}</p>{zone.type==='cities'&&<p className="flex flex-wrap gap-x-2 [overflow-wrap:anywhere]">{zone.cities?.map((city,index)=><bdi key={`${city}-${index}`}>{city}</bdi>)}</p>}<div className="flex flex-wrap gap-x-5 gap-y-2"><span>{t('zoneDeliveryFee')} : <bdi className="font-semibold">{money(zone.delivery_fee??0)}</bdi></span><span>{t('zoneMinOrder')} : {zone.min_order!=null?<bdi className="font-semibold">{money(zone.min_order)}</bdi>:t('zoneMinGlobalPlaceholder')}</span></div></div>;}
function ZoneFeedback({text,error=false}:{text:string;error?:boolean}){return <div role={error?'alert':'status'} className={`flex items-start gap-3 rounded-r-md p-4 text-fs-sm leading-relaxed ${error?'bg-[var(--danger-50)] text-[var(--danger-500)]':'bg-[var(--summary-bg)] text-[var(--summary-fg)]'}`}><CircleAlert className="mt-0.5 size-4 shrink-0" /><span>{text}</span></div>;}
