import { test, expect, type Page } from '@playwright/test';
import { createFixture } from './fixtures.mjs';
import type { DeliveryZone } from '../../src/lib/api';
const seed=():DeliveryZone[]=>[
 {id:1,restaurant_id:1,name:'Centre — livraison de proximité',type:'radius',is_active:true,center_lat:32.01,center_lng:34.75,radius_m:5000,delivery_fee:0,min_order:null,created_at:'2026-10-01T00:00:00Z'},
 {id:2,restaurant_id:1,name:'Villes et codes postaux',type:'cities',is_active:false,cities:['Tel Aviv','01234'],delivery_fee:12.5,min_order:0,created_at:'2026-10-02T00:00:00Z'},
 {id:3,restaurant_id:1,name:'Secteur historique',type:'polygon',is_active:false,polygon:[[34.74,32],[34.8,32],[34.8,32.06]],delivery_fee:null,min_order:40,created_at:'2026-10-03T00:00:00Z'},
 {id:4,restaurant_id:1,name:'Zone réservée à la tournée',type:'cities',is_active:true,cities:['Ville tournée'],tour_only:true,created_at:'2026-10-04T00:00:00Z'},
];
const runtimeErrors=new WeakMap<Page,string[]>();
test.afterEach(async({page})=>{expect(runtimeErrors.get(page)??[]).toEqual([]);});
async function install(page:Page,opts:{locale?:string;permissions?:string[]}={}){
 const errors:string[]=[];runtimeErrors.set(page,errors);page.on('pageerror',error=>errors.push(error.message));
 const fixture=createFixture(),writes:{method:string;path:string;body:any;rid:string|undefined;query:string}[]=[];
 const control={zones:seed(),minimum:50,zoneReads:0,settingsReads:0,geoReads:0,failRead:false,failMinimumRead:false,malformed:false,failWrite:false,applyAndFail:false,failAfterWrite:false,conflict:false,geoUnavailable:false,geoFound:true,tileFailure:false,gate:null as Promise<void>|null};
 await page.addInitScript(({locale})=>{localStorage.setItem('foody_restaurant_token','isolated-ui-fixture');localStorage.setItem('foody_restaurant_user',JSON.stringify({id:1,full_name:'Équipe démo',role:'manager',email:'demo@foody.test'}));localStorage.setItem('foody_restaurant_ids','[1,2]');localStorage.setItem('foody-admin-locale',locale);localStorage.setItem('foody_admin_theme',locale==='he'?'dark':'light');},{locale:opts.locale??'fr'});
 await page.route('**/api/v1/**',async route=>{
  const req=route.request(),url=new URL(req.url()),path=url.pathname,method=req.method(),body=req.postDataJSON()??{},rid=req.headers()['x-restaurant-id'];
  if(path==='/api/v1/users/me')return route.fulfill({json:{role_name:'Custom',permissions:opts.permissions??['orders.manage','settings.view','settings.edit'],user:{id:1,full_name:'Équipe démo',role:'manager'}}});
  if(path==='/api/v1/public/geocode'){control.geoReads++;return route.fulfill({status:control.geoUnavailable?503:200,json:control.geoUnavailable?{error:'Synthetic geocode outage'}:control.geoFound?{found:true,lat:32.08,lng:34.82}:{found:false}});}
  if(path.startsWith('/api/v1/delivery/zones')){
   if(method==='GET'){control.zoneReads++;return route.fulfill({status:control.failRead?503:200,json:control.failRead?{error:'Synthetic read failure'}:control.malformed?{}:{zones:control.zones.map(row=>({...row,restaurant_id:Number(rid)}))}});}
   writes.push({method,path,body,rid,query:url.search});if(control.gate)await control.gate;const id=Number(path.split('/')[5]);let result=control.zones.find(row=>row.id===id);
   if(control.conflict)return route.fulfill({status:409,json:{error:'zone used by tour'}});
   if(!control.failWrite||control.applyAndFail){if(method==='DELETE')control.zones=control.zones.filter(row=>row.id!==id);else if(method==='POST'){result={...body,id:Math.max(0,...control.zones.map(row=>row.id))+1,restaurant_id:Number(rid),created_at:'2026-10-04T12:00:00Z'};control.zones.push(result!);}else if(result)Object.assign(result,body);}
   if(control.failAfterWrite)control.failRead=true;
   return control.failWrite?route.fulfill({status:503,json:{error:'Synthetic uncertain write'}}):method==='DELETE'?route.fulfill({status:204,body:''}):route.fulfill({json:{...result,restaurant_id:Number(rid)}});
  }
  if(/\/restaurants\/[12]\/settings$/.test(path)){
   if(method==='GET'){control.settingsReads++;return route.fulfill({status:control.failMinimumRead?503:200,json:control.failMinimumRead?{error:'Synthetic minimum read failure'}:{settings:{restaurant_id:Number(rid),id:1,minimum_order_delivery:control.minimum}}});}
   writes.push({method,path,body,rid,query:url.search});if(control.gate)await control.gate;if(!control.failWrite||control.applyAndFail)control.minimum=body.minimum_order_delivery;if(control.failAfterWrite)control.failMinimumRead=true;return route.fulfill({status:control.failWrite?503:200,json:control.failWrite?{error:'Synthetic uncertain minimum save'}:{settings:{id:1,restaurant_id:Number(rid),minimum_order_delivery:control.minimum}}});
  }
  const result=fixture.response(req.url(),method,body,Number(rid)||1);if(/^\/api\/v1\/restaurants\/[12]$/.test(path)&&result.json&&'restaurant'in result.json&&result.json.restaurant)Object.assign(result.json.restaurant,{address:'Adresse de démonstration',currency:'ILS'});return route.fulfill({status:result.status??200,json:result.json??{}});
 });
 await page.route('**/*',route=>{const url=new URL(route.request().url());if(['localhost','127.0.0.1'].includes(url.hostname))return route.fallback();if(url.hostname.endsWith('.tile.openstreetmap.org'))return control.tileFailure?route.abort():route.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="256" height="256"><rect width="256" height="256" fill="#edf1f3"/><path d="M0 80H256M90 0V256" stroke="#c4cdd3" stroke-width="8"/><text x="110" y="180" font-size="10" fill="#526575">Carte simulée</text></svg>'});return route.abort();});
 return {control,writes,fixture};
}
const dialog=(page:Page)=>page.getByRole('dialog');
const save=(page:Page)=>dialog(page).getByRole('button',{name:/^Enregistrer$|^Enregistrement/});
const minimumInput=(page:Page)=>page.getByRole('textbox',{name:'Commande minimum par défaut (₪)',exact:true});
const verify=(page:Page)=>page.getByRole('button',{name:'Vérifier les données enregistrées',exact:true});
async function open(page:Page,rid=1){await page.goto(`/${rid}/settings/delivery`);await expect(page.getByRole('button',{name:seed()[0].name,exact:true})).toBeVisible();}
async function edit(page:Page,n=0){await page.getByRole('button',{name:seed()[n].name,exact:true}).click();}
for(const [locale,width] of [['fr',375],['he',1440],['en',820]] as const)test(`delivery zones responsive ${locale} ${width}`,async({page},info)=>{const state=await install(page,{locale});await page.setViewportSize({width,height:1000});await open(page);await expect(page.getByRole('button',{name:seed()[3].name,exact:true})).toHaveCount(0);if(width>=768)await expect(page.locator('.leaflet-container')).toBeVisible();await page.screenshot({path:info.outputPath(`delivery-zones-list-${locale}.png`)});await edit(page);await expect(dialog(page)).toHaveCSS('transform','none');await expect(dialog(page).locator('.leaflet-container')).toBeVisible();expect(await dialog(page).evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true);await page.screenshot({path:info.outputPath(`delivery-zones-editor-${locale}.png`),animations:'disabled'});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(state.fixture.unhandled).toEqual([]);});
test('delivery order-only roles can manage zones without loading protected restaurant settings',async({page})=>{const state=await install(page,{permissions:['orders.manage']});await open(page);await expect(minimumInput(page)).toHaveCount(0);expect(state.control.settingsReads).toBe(0);await page.goto('/1/dashboard');await expect(page.getByRole('link',{name:'Paramètres',exact:true})).toHaveAttribute('href','/1/settings/delivery');});
test('delivery settings-only viewer sees readonly minimum without requesting order-managed zones',async({page})=>{const state=await install(page,{permissions:['settings.view']});await page.goto('/1/settings/delivery');await expect(minimumInput(page)).toHaveValue('50');await expect(minimumInput(page)).toBeDisabled();await expect(page.getByText(/La gestion des zones nécessite/)).toBeVisible();await expect(page.getByRole('button',{name:'Ajouter une zone',exact:true})).toHaveCount(0);expect(state.control.zoneReads).toBe(0);expect(state.control.geoReads).toBe(0);expect(state.writes).toHaveLength(0);});
test('delivery zone and minimum failures remain independent and retryable',async({page})=>{const state=await install(page);state.control.failRead=true;await page.goto('/1/settings/delivery');await expect(page.getByText('Impossible de charger les zones de livraison.',{exact:true})).toBeVisible();await expect(minimumInput(page)).toHaveValue('50');state.control.failRead=false;state.control.malformed=true;await page.getByRole('button',{name:'Réessayer',exact:true}).click();await expect(page.getByText('Impossible de charger les zones de livraison.',{exact:true})).toBeVisible();state.control.malformed=false;await page.getByRole('button',{name:'Réessayer',exact:true}).click();await expect(page.getByRole('button',{name:seed()[0].name,exact:true})).toBeVisible();});
test('delivery minimum load error never becomes an editable zero fallback',async({page})=>{const state=await install(page);state.control.failMinimumRead=true;await open(page);await expect(page.getByText('Impossible de charger le minimum de commande global.',{exact:true})).toBeVisible();await expect(minimumInput(page)).toHaveCount(0);state.control.failMinimumRead=false;await page.getByRole('button',{name:'Réessayer',exact:true}).click();await expect(minimumInput(page)).toHaveValue('50');});
test('delivery radius price edit preserves its original centre and explicit zero minimum',async({page})=>{const state=await install(page);await open(page,2);await edit(page);await dialog(page).getByRole('textbox',{name:'Frais de livraison (₪)',exact:true}).fill('15.5');await dialog(page).getByRole('textbox',{name:'Commande minimum (₪)',exact:true}).fill('0');await save(page).click();await expect(dialog(page)).toHaveCount(0);expect(state.writes).toHaveLength(1);expect(state.writes[0]).toMatchObject({method:'PUT',path:'/api/v1/delivery/zones/1',rid:'2',query:'?restaurant_id=2',body:{center_lat:32.01,center_lng:34.75,radius_m:5000,delivery_fee:15.5,min_order:0}});expect(state.writes[0].body.tour_only).toBeUndefined();});
test('delivery radius can explicitly adopt the current restaurant origin',async({page})=>{const state=await install(page);await open(page);await edit(page);await dialog(page).getByRole('button',{name:'Utiliser l’adresse actuelle du restaurant comme centre',exact:true}).click();await save(page).click();await expect(dialog(page)).toHaveCount(0);expect(state.writes[0].body).toMatchObject({center_lat:32.08,center_lng:34.82});});
test('delivery geocoding outage preserves an existing zone but blocks a new radius without origin',async({page})=>{const state=await install(page);state.control.geoUnavailable=true;await open(page);await edit(page);await expect(dialog(page).getByText(/La recherche d’adresse est momentanément indisponible/)).toBeVisible();await dialog(page).getByRole('textbox',{name:'Frais de livraison (₪)',exact:true}).fill('9');await save(page).click();await expect(dialog(page)).toHaveCount(0);await page.getByRole('button',{name:'Ajouter une zone',exact:true}).click();await dialog(page).getByRole('textbox',{name:'Nom de la zone',exact:true}).fill('Nouveau rayon');await save(page).click();await expect(dialog(page).getByText(/Un rayon nécessite un centre valide/)).toBeVisible();expect(state.writes).toHaveLength(1);await expect(page.locator('.foody-zone-home')).toHaveCount(0);state.control.geoUnavailable=false;await dialog(page).getByRole('button',{name:'Réessayer',exact:true}).click();await dialog(page).getByRole('button',{name:'Utiliser l’adresse actuelle du restaurant comme centre',exact:true}).click();await save(page).click();await expect(dialog(page)).toHaveCount(0);expect(state.writes).toHaveLength(2);});
test('delivery city draft handles postal codes, duplicate names and unadded text',async({page},info)=>{const state=await install(page);await page.setViewportSize({width:375,height:1000});await open(page);await edit(page,1);const city=dialog(page).getByRole('textbox',{name:'Ville ou code postal',exact:true});await city.fill(' tel aviv ');await dialog(page).getByRole('button',{name:'Ajouter',exact:true}).click();await expect(dialog(page).getByText('Cette ville ou ce code postal est déjà inclus.',{exact:true})).toBeVisible();await city.fill('05678');await save(page).click();await expect(dialog(page).getByText(/Ajoutez la ville saisie ou videz le champ/)).toBeVisible();await city.press('Enter');await expect(dialog(page)).toHaveCSS('transform','none');await page.screenshot({path:info.outputPath('delivery-zones-cities-fr.png'),animations:'disabled'});await save(page).click();await expect(dialog(page)).toHaveCount(0);expect(state.writes[0].body.cities).toEqual(['Tel Aviv','01234','05678']);expect(state.writes[0].body.min_order).toBe(0);});
test('delivery legacy polygon survives a fee edit and can be viewed without new drawing tools',async({page})=>{const state=await install(page);await open(page);await edit(page,2);await expect(dialog(page).getByText(/Polygone enregistré · 3 points/)).toBeVisible();await dialog(page).getByRole('textbox',{name:'Frais de livraison (₪)',exact:true}).fill('7');await save(page).click();await expect(dialog(page)).toHaveCount(0);expect(state.writes[0].body.polygon).toEqual(seed()[2].polygon);expect(state.writes[0].body.type).toBe('polygon');});
test('delivery invalid radius and negative fee do not mutate',async({page})=>{const state=await install(page);await open(page);await edit(page);await dialog(page).getByRole('textbox',{name:'Rayon (km)',exact:true}).fill('0.0001');await save(page).click();await expect(dialog(page).getByText(/Un rayon nécessite un centre valide/)).toBeVisible();await dialog(page).getByRole('textbox',{name:'Rayon (km)',exact:true}).fill('5');await dialog(page).getByRole('textbox',{name:'Frais de livraison (₪)',exact:true}).fill('-2');await save(page).click();await expect(dialog(page).getByRole('alert')).toBeVisible();expect(state.writes).toHaveLength(0);});
test('delivery zone draft and pending city guard dismissal',async({page})=>{const state=await install(page);await open(page);await edit(page,1);await dialog(page).getByRole('textbox',{name:'Ville ou code postal',exact:true}).fill('Ville non ajoutée');await dialog(page).getByRole('button',{name:'Fermer',exact:true}).click();await page.getByRole('alertdialog').getByRole('button',{name:'Annuler',exact:true}).click();await expect(dialog(page).getByRole('textbox',{name:'Ville ou code postal',exact:true})).toHaveValue('Ville non ajoutée');await dialog(page).getByRole('button',{name:'Fermer',exact:true}).click();await page.getByRole('alertdialog').getByRole('button',{name:'Abandonner les modifications',exact:true}).click();await expect(dialog(page)).toHaveCount(0);expect(state.writes).toHaveLength(0);});
test('delivery minimum serializes a scoped zero save and never sends other settings',async({page})=>{const state=await install(page);await open(page,2);await minimumInput(page).fill('');await page.getByRole('button',{name:'Enregistrer',exact:true}).click();await expect(page.getByText(/Indiquez 0 pour aucun minimum/)).toBeVisible();await minimumInput(page).fill('0');let release!:()=>void;state.control.gate=new Promise<void>(resolve=>{release=resolve;});await page.getByRole('button',{name:'Enregistrer',exact:true}).evaluate((el:HTMLButtonElement)=>{el.click();el.click();});await expect(minimumInput(page)).toBeDisabled();release();state.control.gate=null;await expect(page.getByText('Enregistré !',{exact:true})).toBeVisible();expect(state.writes).toEqual([{method:'PUT',path:'/api/v1/restaurants/2/settings',rid:'2',query:'',body:{minimum_order_delivery:0}}]);});
for(const kind of ['create','update','delete','minimum'])test(`delivery uncertain ${kind} reconciles by GET without repeated writes`,async({page})=>{const state=await install(page);state.control.failWrite=true;state.control.applyAndFail=true;state.control.failAfterWrite=true;await open(page);if(kind==='minimum'){await minimumInput(page).fill('0');await page.getByRole('button',{name:'Enregistrer',exact:true}).click();}else if(kind==='delete'){await page.getByRole('button',{name:`Supprimer · ${seed()[1].name}`,exact:true}).click();await page.getByRole('alertdialog').getByRole('button',{name:'Supprimer',exact:true}).click();}else{if(kind==='create'){await page.getByRole('button',{name:'Ajouter une zone',exact:true}).click();await dialog(page).getByRole('textbox',{name:'Nom de la zone',exact:true}).fill('Nouvelle ville');await dialog(page).getByRole('combobox',{name:'Type de zone',exact:true}).selectOption('cities');await dialog(page).getByRole('textbox',{name:'Ville ou code postal',exact:true}).fill('Ville démo');await dialog(page).getByRole('button',{name:'Ajouter',exact:true}).click();}else{await edit(page);await dialog(page).getByRole('textbox',{name:'Frais de livraison (₪)',exact:true}).fill('8');}await save(page).click();}await expect(verify(page)).toBeVisible();await verify(page).click();await expect(page.getByText(/Impossible de vérifier/)).toBeVisible();state.control.failRead=false;state.control.failMinimumRead=false;await verify(page).click();await expect(verify(page)).toHaveCount(0);await expect(dialog(page)).toHaveCount(0);expect(state.writes).toHaveLength(1);});
test('delivery differing zone readback preserves the draft until confirmed adoption',async({page},info)=>{const state=await install(page);state.control.failWrite=true;await open(page);await edit(page);await dialog(page).getByRole('textbox',{name:'Frais de livraison (₪)',exact:true}).fill('10');await save(page).click();await verify(page).click();await expect(dialog(page).getByRole('textbox',{name:'Frais de livraison (₪)',exact:true})).toHaveValue('10');await page.screenshot({path:info.outputPath('delivery-zones-recovery-fr.png'),animations:'disabled'});await dialog(page).getByRole('button',{name:'Utiliser la version enregistrée',exact:true}).click();await page.getByRole('alertdialog').getByRole('button',{name:'Utiliser la version enregistrée',exact:true}).click();await expect(dialog(page).getByRole('textbox',{name:'Frais de livraison (₪)',exact:true})).toHaveValue('0');await expect(save(page)).toBeDisabled();expect(state.writes).toHaveLength(1);});
test('delivery last active zone deactivation explains the actual coverage rule',async({page},info)=>{const state=await install(page);await open(page);await page.getByRole('checkbox',{name:`Zone active · ${seed()[0].name}`,exact:true}).click();await expect(page.getByRole('alertdialog').getByText(/Sans zone classique active/)).toBeVisible();await page.getByRole('alertdialog').getByRole('button',{name:'Annuler',exact:true}).click();expect(state.writes).toHaveLength(0);await page.getByRole('checkbox',{name:`Zone active · ${seed()[0].name}`,exact:true}).click();await expect(page.getByRole('alertdialog')).toHaveCSS('opacity','1');await page.screenshot({path:info.outputPath('delivery-zones-disable-fr.png'),animations:'disabled'});await page.getByRole('alertdialog').getByRole('button',{name:'Désactiver la zone',exact:true}).click();await expect(page.getByText(/Sans zone classique active/)).toBeVisible();expect(state.writes[0].body.is_active).toBe(false);expect(state.writes[0].body.radius_m).toBe(5000);});
test('delivery tour protection is explained without deletion or automatic retry',async({page})=>{const state=await install(page);state.control.conflict=true;await open(page);await page.getByRole('button',{name:`Supprimer · ${seed()[0].name}`,exact:true}).click();await page.getByRole('alertdialog').getByRole('button',{name:'Supprimer',exact:true}).click();await expect(page.getByText(/Cette ville est utilisée par une tournée à venir/)).toBeVisible();expect(state.writes).toHaveLength(1);expect(state.control.zones).toHaveLength(4);});
test('delivery filtering and mobile map preview remain usable with failed tiles',async({page})=>{const state=await install(page);state.control.tileFailure=true;await page.setViewportSize({width:375,height:1000});await open(page);await page.getByRole('searchbox').fill('01234');await expect(page.getByRole('button',{name:seed()[1].name,exact:true})).toBeVisible();await expect(page.getByRole('button',{name:seed()[0].name,exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Afficher l’aperçu de la carte',exact:true}).click();await expect(page.getByText(/Le fond de carte est indisponible/)).toBeVisible();expect(state.writes).toHaveLength(0);});
test('delivery language change preserves loaded data without refetching zones or minimum',async({page})=>{const state=await install(page);await open(page);await expect(minimumInput(page)).toHaveValue('50');const reads=[state.control.zoneReads,state.control.settingsReads,state.control.geoReads];await page.getByRole('button',{name:'Foody · Profil',exact:true}).click();await dialog(page).getByRole('button',{name:'עברית',exact:true}).click();await page.keyboard.press('Escape');expect([state.control.zoneReads,state.control.settingsReads,state.control.geoReads]).toEqual(reads);});
test('delivery no classic zones is distinct from a tour-only inventory',async({page})=>{const state=await install(page);state.control.zones=[seed()[3]];await page.goto('/1/settings/delivery');await expect(page.getByText('Aucune zone de livraison classique configurée',{exact:true})).toBeVisible();await expect(page.getByText(/Sans zone classique active/)).toBeVisible();expect(state.writes).toHaveLength(0);});
test('delivery differing minimum readback preserves input until explicit adoption',async({page})=>{const state=await install(page);state.control.failWrite=true;await open(page);await minimumInput(page).fill('25');await page.getByRole('button',{name:'Enregistrer',exact:true}).click();await verify(page).click();await expect(minimumInput(page)).toHaveValue('25');await expect(page.getByText(/Le minimum enregistré diffère/)).toBeVisible();await page.getByRole('button',{name:'Utiliser la version enregistrée',exact:true}).click();await page.getByRole('alertdialog').getByRole('button',{name:'Annuler',exact:true}).click();await expect(minimumInput(page)).toHaveValue('25');await page.getByRole('button',{name:'Utiliser la version enregistrée',exact:true}).click();await page.getByRole('alertdialog').getByRole('button',{name:'Utiliser la version enregistrée',exact:true}).click();await expect(minimumInput(page)).toHaveValue('50');expect(state.writes).toHaveLength(1);});
test('delivery zone save freezes the draft and prevents simultaneous writes',async({page})=>{const state=await install(page);await open(page);await edit(page);await dialog(page).getByRole('textbox',{name:'Frais de livraison (₪)',exact:true}).fill('18');let release!:()=>void;state.control.gate=new Promise<void>(resolve=>{release=resolve;});await save(page).evaluate((el:HTMLButtonElement)=>{el.click();el.click();});await expect(dialog(page).getByRole('button',{name:'Fermer',exact:true})).toBeDisabled();await expect(dialog(page).getByRole('textbox',{name:'Nom de la zone',exact:true})).toBeDisabled();release();state.control.gate=null;await expect(dialog(page)).toHaveCount(0);expect(state.writes).toHaveLength(1);});
