import { test, expect, type Page } from '@playwright/test';
import { createFixture } from './fixtures.mjs';
import type { RestaurantDevice } from '../../src/lib/api';
const ids = ['11111111-1111-4111-8111-111111111111', '22222222-2222-4222-8222-222222222222', '33333333-3333-4333-8333-333333333333'];
const device = (n: number): RestaurantDevice => ({ id: ids[n], restaurant_id: 1, kind: n === 0 ? 'tablet' : n === 1 ? 'printer' : 'payment_terminal', system_name: ['Tablette de démonstration — cuisine et accueil', 'Imprimante de démonstration', 'Victa démo'][n], display_name: n === 0 ? 'Accueil' : '', manufacturer: 'Démo', model: 'Modèle test', os_name: n === 1 ? '' : 'Android', os_version: 'Demo', battery_level: n === 0 ? 0 : undefined, identifier: ids[n], status: n === 1 ? 'attention' : 'online', last_seen_at: '2026-10-04T14:00:00Z', created_at: '2026-10-01T08:00:00Z', updated_at: '2026-10-04T14:00:00Z', capabilities: n === 0 ? [] : n === 1 ? [{ type: 'printer', status: 'attention' }] : [{ type: 'printer', status: 'online' }, { type: 'payment_terminal', status: 'online' }], components: n === 0 ? [{ type: 'application', status: 'active', details: { application: 'foody_pos', version: 'Demo', platform: 'android', last_active_at: '2026-10-04T14:00:00Z' } }] : [{ type: 'printer', status: 'online', details: { printer_id: `printer-${n}`, pending_job_count: n === 1 ? 2 : 0, enabled: true, paper_width_dots: 384, connection_type: n === 2 ? 'integrated' : 'network' } }, { type: 'network', status: 'active', details: { ip_address: '192.0.2.10', port: 9100 } }], connections: n === 0 ? [{ id: ids[1], kind: 'printer', system_name: 'Imprimante de démonstration', display_name: '', status: 'attention' }] : [], profile_names: ['Cuisine démo'] });
async function install(page: Page, options: { locale?: string; permissions?: string[] } = {}) {
  const fixture = createFixture(), writes: { method: string; path: string; body: any; rid: string | undefined }[] = [];
  const control = { rows: [device(0), device(1), device(2)], reads: 0, failRead: false, malformed: false, failWrite: false, applyAndFail: false, failAfterWrite: false, failDeleteIds: [] as string[], gate: null as Promise<void> | null };
  await page.addInitScript(({ locale }) => { localStorage.setItem('foody_restaurant_token', 'isolated-ui-fixture'); localStorage.setItem('foody_restaurant_user', JSON.stringify({ id: 1, full_name: 'Équipe démo', role: 'manager', email: 'demo@foody.test' })); localStorage.setItem('foody_restaurant_ids', '[1,2]'); localStorage.setItem('foody-admin-locale', locale); localStorage.setItem('foody_admin_theme', locale === 'he' ? 'dark' : 'light'); }, { locale: options.locale ?? 'fr' });
  await page.route('**/api/v1/**', async route => {
    const request = route.request(), path = new URL(request.url()).pathname, method = request.method(), body = request.postDataJSON() ?? {}, rid = request.headers()['x-restaurant-id'];
    if (path === '/api/v1/users/me') return route.fulfill({ json: { role_name: 'Custom', permissions: options.permissions ?? ['settings.view', 'settings.edit', 'printers.view', 'printers.manage', 'shifts.manage', 'payments.manage'], user: { id: 1, full_name: 'Équipe démo', role: 'manager' } } });
    if (/\/restaurants\/[12]\/devices(?:\/|$)/.test(path)) {
      if (method === 'GET') { control.reads++; return route.fulfill({ status: control.failRead ? 503 : 200, json: control.failRead ? { error: 'Synthetic failure' } : control.malformed ? {} : { devices: control.rows.map(row => ({ ...row, restaurant_id: Number(rid) })) } }); }
      writes.push({ method, path, body, rid }); if (control.gate) await control.gate; const id = path.split('/').pop(), fail = control.failWrite || control.failDeleteIds.includes(id!); let row = control.rows.find(row => row.id === id);
      if (!fail || control.applyAndFail) { if (method === 'DELETE') control.rows = control.rows.filter(row => row.id !== id); else if (row) Object.assign(row, body); }
      if (control.failAfterWrite) control.failRead = true;
      return route.fulfill({ status: fail ? 400 : 200, json: fail ? { error: 'device operation failed', details: 'printer has unfinished print jobs' } : method === 'PATCH' ? { device: { ...row, restaurant_id: Number(rid) } } : {} });
    }
    if (path.includes('/printing/printers/') && method === 'POST') {
      writes.push({ method, path, body, rid }); if (control.gate) await control.gate;
      const printerId = path.split('/').at(-2)!;
      if (path.endsWith('/cancel-pending') && (!control.failWrite || control.applyAndFail)) for (const row of control.rows) for (const component of row.components) if (component.details.printer_id === printerId) component.details.pending_job_count = 0;
      if (control.failAfterWrite) control.failRead = true;
      return route.fulfill({ status: control.failWrite ? 503 : 200, json: control.failWrite ? { error: 'Synthetic uncertain printer request' } : path.endsWith('/test') ? { job: { id: 'job-demo', kind: 'test', current_printer_id: printerId, state: 'queued', attempts: 0, created_at: '2026-10-04T14:00:00Z' } } : { cancelled_count: 2, cancelled_job_ids: ['job-1', 'job-2'] } });
    }
    const result = fixture.response(request.url(), method, body, Number(rid) || 1); return route.fulfill({ json: result.json ?? {}, status: result.status ?? 200 });
  });
  await page.route('**/*', route => ['localhost', '127.0.0.1'].includes(new URL(route.request().url()).hostname) ? route.fallback() : route.abort());
  return { control, writes, fixture };
}
const drawer = (page: Page) => page.getByRole('dialog');
const renameModal = (page: Page) => page.getByRole('dialog', { name: 'Nom d’affichage de l’appareil', exact: true });
const save = (page: Page) => renameModal(page).getByRole('button', { name: 'Enregistrer', exact: true });
const verify = (page: Page) => page.getByRole('button', { name: 'Vérifier l’inventaire', exact: true });
async function open(page: Page, n = 0, rid = 1) { await page.goto(`/${rid}/settings/devices`); await page.getByRole('button', { name: device(n).system_name, exact: true }).click(); }
async function editName(page: Page) { await drawer(page).getByRole('button', { name: 'Modifier', exact: true }).click(); }
async function rename(page: Page, name = 'Nom modifié') { await editName(page); await renameModal(page).getByRole('textbox').fill(name); await save(page).click(); }
async function action(page: Page, name: string) { await drawer(page).getByRole('button', { name: 'Actions', exact: true }).click(); await page.getByRole('menuitem', { name, exact: true }).click(); }
for (const locale of ['fr', 'he']) test(`device inventory responsive filters, physical devices and detail ${locale}`, async ({ page }, info) => {
  const state = await install(page, { locale }); await page.setViewportSize({ width: locale === 'fr' ? 375 : 1440, height: 1000 }); await page.goto('/1/settings/devices'); await expect(page.getByRole('button', { name: device(0).system_name, exact: true })).toBeVisible(); await page.screenshot({ path: info.outputPath(`device-inventory-list-${locale}.png`) }); await page.getByRole('button', { name: device(0).system_name, exact: true }).click(); await expect(drawer(page)).toHaveCSS('transform', 'none'); await page.screenshot({ path: info.outputPath(`device-inventory-detail-${locale}.png`), animations: 'disabled' }); await expect(drawer(page).getByText('0%', { exact: true })).toBeVisible(); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); expect(state.fixture.unhandled).toEqual([]);
});
test('device inventory filtering, search and column visibility preserve physical identity', async ({ page }) => {
  const state = await install(page); await page.goto('/1/settings/devices'); await page.locator('[data-list-toolbar]').getByRole('button', { name: 'Type d’appareil', exact: true }).click(); await drawer(page).getByRole('checkbox', { name: 'Imprimante', exact: true }).check(); await drawer(page).getByRole('button', { name: 'Appliquer', exact: true }).click(); await expect(page.getByRole('button', { name: device(0).system_name, exact: true })).toHaveCount(0); await expect(page.getByRole('button', { name: 'Victa démo', exact: true })).toBeVisible(); await page.getByRole('searchbox').fill('démo introuvable'); await expect(page.getByText('Aucun appareil ne correspond à ces filtres.', { exact: true })).toBeVisible(); await page.getByRole('searchbox').fill(''); await page.getByRole('button', { name: 'Tous les filtres', exact: true }).click(); await drawer(page).getByRole('button', { name: 'Réinitialiser tous les filtres', exact: true }).click(); await drawer(page).getByRole('button', { name: /^Applications installées/ }).click(); await drawer(page).getByRole('checkbox', { name: 'FoodyPOS', exact: true }).check(); await drawer(page).getByRole('button', { name: 'Appliquer', exact: true }).click(); await expect(page.getByRole('button', { name: 'Victa démo', exact: true })).toHaveCount(0); await page.getByRole('button', { name: 'Colonnes', exact: true }).click(); await page.getByRole('menuitemcheckbox', { name: 'Identifiant de l’appareil', exact: true }).click(); await expect(page.getByRole('menuitemcheckbox', { name: 'Identifiant de l’appareil', exact: true })).toHaveAttribute('aria-checked', 'true'); await page.keyboard.press('Escape'); await expect(page.getByRole('columnheader', { name: 'Identifiant de l’appareil', exact: true })).toBeVisible(); expect(state.writes).toHaveLength(0);
});
test('device inventory pagination selection and sorting remain usable', async ({ page }) => {
  const state = await install(page); state.control.rows = Array.from({ length: 12 }, (_, n) => ({ ...device(0), id: `device-${n}`, system_name: `Tablette ${String(n).padStart(2, '0')}` })); await page.goto('/1/settings/devices'); await page.getByRole('button', { name: 'Actions', exact: true }).click(); await page.getByRole('menuitem', { name: 'Trier par', exact: true }).click(); await page.getByRole('combobox', { name: 'Trier par', exact: true }).selectOption('name'); await page.getByRole('button', { name: 'Passer en ordre croissant', exact: true }).click(); await page.keyboard.press('Escape'); await expect(page.getByRole('columnheader', { name: 'Nom', exact: true })).toHaveAttribute('aria-sort', 'ascending'); await page.getByRole('checkbox', { name: 'Tout sélectionner', exact: true }).check(); await expect(page.getByText('10 sélectionnés', { exact: true })).toBeVisible(); await page.getByRole('button', { name: 'Suivant', exact: true }).click(); await expect(page.getByRole('button', { name: 'Tablette 11', exact: true })).toBeVisible(); await expect(page.getByRole('checkbox', { name: 'Tout sélectionner', exact: true })).not.toBeChecked(); await page.getByRole('button', { name: 'Actions', exact: true }).click(); await page.getByRole('menuitem', { name: 'Effacer la sélection', exact: true }).click(); expect(state.writes).toHaveLength(0);
});
test('device inventory initial error, malformed data and empty inventory are distinct', async ({ page }) => {
  const state = await install(page); state.control.failRead = true; await page.goto('/1/settings/devices'); await expect(page.getByText('Impossible de charger les appareils.', { exact: true })).toBeVisible(); await expect(page.getByText('Aucun appareil', { exact: true })).toHaveCount(0); state.control.failRead = false; state.control.malformed = true; await page.getByRole('button', { name: 'Réessayer', exact: true }).click(); await expect(page.getByText('Impossible de charger les appareils.', { exact: true })).toBeVisible(); state.control.malformed = false; state.control.rows = []; await page.getByRole('button', { name: 'Réessayer', exact: true }).click(); await expect(page.getByText('Aucun appareil', { exact: true })).toBeVisible(); expect(state.writes).toHaveLength(0);
});
test('device inventory name save serializes, scopes and permits clearing an alias', async ({ page }, info) => {
  const state = await install(page); await open(page, 0, 2); await editName(page); await expect(save(page)).toBeDisabled(); await renameModal(page).getByRole('textbox').fill('   '); await page.screenshot({ path: info.outputPath('device-inventory-rename-fr.png') }); let release!: () => void; state.control.gate = new Promise<void>(resolve => { release = resolve; }); await save(page).evaluate((button: HTMLButtonElement) => { button.click(); button.click(); }); await expect(save(page)).toBeDisabled(); await expect(renameModal(page).getByRole('button', { name: 'Fermer', exact: true })).toBeDisabled(); release(); state.control.gate = null; await expect(renameModal(page)).toHaveCount(0); await expect(drawer(page).getByText('Nom d’affichage enregistré.', { exact: true })).toBeVisible(); expect(state.writes).toEqual([{ method: 'PATCH', path: `/api/v1/restaurants/2/devices/${ids[0]}`, body: { display_name: '' }, rid: '2' }]);
});
test('device inventory polling and locale do not replace a name draft', async ({ page }) => {
  const state = await install(page); await page.clock.install({ time: new Date('2026-10-04T14:00:00Z') }); await open(page); await editName(page); await renameModal(page).getByRole('textbox').fill('Brouillon conservé'); const reads = state.control.reads; state.control.rows[0].display_name = 'Nom distant'; await page.clock.fastForward(31_000); await expect.poll(() => state.control.reads).toBeGreaterThan(reads); await expect(renameModal(page).getByRole('textbox')).toHaveValue('Brouillon conservé'); await page.keyboard.press('Escape'); await page.getByRole('alertdialog').getByRole('button', { name: 'Annuler', exact: true }).click(); await expect(renameModal(page).getByRole('textbox')).toHaveValue('Brouillon conservé'); expect(state.writes).toHaveLength(0);
});
test('device inventory name length validates before a request', async ({ page }) => {
  const state = await install(page); await open(page); await editName(page); await renameModal(page).getByRole('textbox').fill('x'.repeat(121)); await save(page).click(); await expect(renameModal(page).getByText('Le nom peut contenir jusqu’à 120 caractères.', { exact: true })).toBeVisible(); expect(state.writes).toHaveLength(0);
});
for (const applied of [true, false]) test(`device inventory uncertain rename recovers without repeating PATCH ${applied}`, async ({ page }) => {
  const state = await install(page); state.control.failWrite = true; state.control.applyAndFail = applied; await open(page); await rename(page); await expect(verify(page)).toBeVisible(); await expect(save(page)).toBeDisabled(); state.control.failRead = true; await verify(page).click(); await expect(renameModal(page).getByText('La vérification a échoué. Réessayez sans répéter l’action.', { exact: true })).toBeVisible(); state.control.failRead = false; await verify(page).click(); if (applied) { await expect(renameModal(page)).toHaveCount(0); await expect(drawer(page).getByText('Le nom enregistré correspond à votre saisie.', { exact: true })).toBeVisible(); } else { await expect(renameModal(page).getByRole('textbox')).toHaveValue('Nom modifié'); await renameModal(page).getByRole('button', { name: 'Utiliser le nom enregistré', exact: true }).click(); await expect(renameModal(page).getByRole('textbox')).toHaveValue('Accueil'); await expect(save(page)).toBeDisabled(); } expect(state.writes).toHaveLength(1);
});
test('device inventory read-only details and mixed capabilities require all permissions', async ({ page }) => {
  const state = await install(page, { permissions: ['printers.view', 'printers.manage'] }); await open(page, 2); await expect(drawer(page).getByText('Intégrée à ce Victa', { exact: true })).toHaveCount(2); await expect(drawer(page).getByRole('button', { name: 'Modifier', exact: true })).toHaveCount(0); await drawer(page).getByRole('button', { name: 'Actions', exact: true }).click(); await expect(page.getByRole('menuitem', { name: 'Oublier', exact: true })).toHaveCount(0); await expect(page.getByRole('menuitem', { name: 'Imprimer un ticket test', exact: true })).toBeVisible(); expect(state.writes).toHaveLength(0);
});
test('device inventory read-only role cannot test, cancel, rename or forget a printer', async ({ page }) => {
  const state = await install(page, { permissions: ['printers.view'] }); await open(page, 1); await expect(drawer(page).getByRole('button', { name: 'Modifier', exact: true })).toHaveCount(0); await expect(drawer(page).getByRole('button', { name: 'Annuler les impressions en attente', exact: true })).toHaveCount(0); await drawer(page).getByRole('button', { name: 'Actions', exact: true }).click(); await expect(page.getByRole('menuitem', { name: 'Imprimer un ticket test', exact: true })).toHaveCount(0); await expect(page.getByRole('menuitem', { name: 'Oublier', exact: true })).toHaveCount(0); expect(state.writes).toHaveLength(0);
});
test('device inventory test ticket sends locale once and does not claim physical print', async ({ page }) => {
  const state = await install(page); await open(page, 1, 2); let release!: () => void; state.control.gate = new Promise<void>(resolve => { release = resolve; }); await drawer(page).getByRole('button', { name: 'Actions', exact: true }).click(); await page.getByRole('menuitem', { name: 'Imprimer un ticket test', exact: true }).evaluate((button: HTMLElement) => { button.click(); button.click(); }); await expect(drawer(page).getByRole('button', { name: 'Actions', exact: true })).toBeDisabled(); release(); state.control.gate = null; await expect(drawer(page).getByText('Ticket test placé dans la file d’impression.', { exact: true })).toBeVisible(); expect(state.writes).toEqual([{ method: 'POST', path: '/api/v1/restaurants/2/printing/printers/printer-1/test', rid: '2', body: { locale: 'fr' } }]);
});
test('device inventory lost test response asks for hardware inspection before another explicit test', async ({ page }) => {
  const state = await install(page); state.control.failWrite = true; await open(page, 1); await action(page, 'Imprimer un ticket test'); await expect(drawer(page).getByText(/Vérifiez l’imprimante avant de demander un autre test/)).toBeVisible(); await expect(drawer(page).getByRole('button', { name: 'Actions', exact: true })).toBeDisabled(); await drawer(page).getByRole('button', { name: 'J’ai vérifié l’imprimante', exact: true }).click(); await expect(drawer(page).getByRole('button', { name: 'Actions', exact: true })).toBeEnabled(); expect(state.writes).toHaveLength(1);
});
test('device inventory cancel queue distinguishes confirmed action from failed refresh', async ({ page }, info) => {
  const state = await install(page); state.control.failAfterWrite = true; await open(page, 1); await drawer(page).getByRole('button', { name: 'Annuler les impressions en attente', exact: true }).click(); await expect(page.getByRole('alertdialog')).toHaveCSS('opacity', '1'); await page.screenshot({ path: info.outputPath('device-inventory-cancel-fr.png'), animations: 'disabled' }); await page.getByRole('alertdialog').getByRole('button', { name: 'Annuler les impressions en attente', exact: true }).click(); await expect(drawer(page).getByText('2 impression(s) annulée(s).', { exact: true })).toBeVisible(); await expect(drawer(page).getByText(/La modification est confirmée, mais la liste/)).toBeVisible(); state.control.failRead = false; await drawer(page).getByRole('button', { name: 'Réessayer', exact: true }).click(); await expect(drawer(page).getByRole('button', { name: 'Annuler les impressions en attente', exact: true })).toHaveCount(0); expect(state.writes).toHaveLength(1);
});
test('device inventory uncertain cancellation reads the current queue without repeating POST', async ({ page }) => {
  const state = await install(page); state.control.failWrite = true; state.control.applyAndFail = true; await open(page, 1); await drawer(page).getByRole('button', { name: 'Annuler les impressions en attente', exact: true }).click(); await page.getByRole('alertdialog').getByRole('button', { name: 'Annuler les impressions en attente', exact: true }).click(); await verify(page).click(); await expect(drawer(page).getByText(/Le résultat de l’annulation précédente n’est pas confirmé/)).toBeVisible(); await expect(drawer(page).getByRole('button', { name: 'Annuler les impressions en attente', exact: true })).toHaveCount(0); expect(state.writes).toHaveLength(1);
});
test('device inventory bulk forget retains successful removals and retries only remaining devices', async ({ page }) => {
  const state = await install(page); state.control.failDeleteIds = [ids[1]]; await page.goto('/1/settings/devices'); await page.getByRole('checkbox', { name: 'Tout sélectionner', exact: true }).check(); await page.getByRole('button', { name: 'Actions', exact: true }).click(); await page.getByRole('menuitem', { name: 'Oublier (3)', exact: true }).click(); await page.getByRole('alertdialog').getByRole('button', { name: 'Annuler', exact: true }).click(); expect(state.writes).toHaveLength(0); await page.getByRole('button', { name: 'Actions', exact: true }).click(); await page.getByRole('menuitem', { name: 'Oublier (3)', exact: true }).click(); await page.getByRole('alertdialog').getByRole('button', { name: 'Oublier', exact: true }).click(); await expect(page.getByText('2 appareil(s) retiré(s) de l’inventaire.', { exact: true })).toBeVisible(); await expect(page.getByText(/Cette imprimante a encore des tâches/)).toBeVisible(); await verify(page).click(); await expect(page.getByText(/1 appareil\(s\) de la demande restent/)).toBeVisible(); state.control.failDeleteIds = []; await page.getByRole('button', { name: 'Actions', exact: true }).click(); await page.getByRole('menuitem', { name: 'Oublier (1)', exact: true }).click(); await page.getByRole('alertdialog').getByRole('button', { name: 'Oublier', exact: true }).click(); await expect(page.getByText('Aucun appareil', { exact: true })).toBeVisible(); expect(state.writes.filter(write => write.path.endsWith(ids[0]))).toHaveLength(1); expect(state.writes.filter(write => write.path.endsWith(ids[1]))).toHaveLength(2); expect(state.writes).toHaveLength(4);
});
test('device inventory lost delete response verifies absence without another DELETE', async ({ page }) => {
  const state = await install(page); state.control.failWrite = true; state.control.applyAndFail = true; await open(page); await action(page, 'Oublier'); await page.getByRole('alertdialog').getByRole('button', { name: 'Oublier', exact: true }).click(); await verify(page).click(); await expect(drawer(page)).toHaveCount(0); await expect(page.getByText('Les appareils à vérifier ne figurent plus dans l’inventaire.', { exact: true })).toBeVisible(); expect(state.writes).toHaveLength(1);
});
test('device inventory English empty and connect help retain scoped POS access link', async ({ page }) => {
  const state = await install(page, { locale: 'en' }); state.control.rows = []; await page.goto('/2/settings/devices'); await page.getByRole('button', { name: 'Add a device', exact: true }).click(); await expect(drawer(page).getByRole('link')).toHaveAttribute('href', '/2/staff/devices'); expect(state.writes).toHaveLength(0);
});
test('device inventory locale changes do not refetch data', async ({ page }) => {
  const state = await install(page); await page.goto('/1/settings/devices'); await expect(page.getByRole('button', { name: device(0).system_name, exact: true })).toBeVisible(); const reads = state.control.reads; await page.getByRole('button', { name: 'Atelier Foody', exact: true }).click(); await page.getByRole('dialog').getByRole('combobox').selectOption('he'); await page.keyboard.press('Escape'); await expect(page.getByRole('heading', { name: 'מכשירים', exact: true })).toBeVisible(); expect(state.control.reads).toBe(reads);
});

test('device inventory mobile filters and navigation expose the allowed hardware route', async ({ page }) => {
  const state = await install(page, { permissions: ['printers.view'] });
  await page.setViewportSize({ width: 375, height: 1000 });
  await page.goto('/1/settings/devices');
  await page.getByRole('button', { name: 'Type d’appareil', exact: true }).click();
  await drawer(page).getByRole('checkbox', { name: 'Imprimante', exact: true }).check();
  await drawer(page).getByRole('button', { name: 'Appliquer', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Victa démo', exact: true })).toBeVisible();
  await page.setViewportSize({ width: 1440, height: 1000 });
  const nav = page.getByRole('navigation', { name: 'Navigation principale' });
  await expect(nav.getByRole('link', { name: 'Appareils', exact: true })).toHaveAttribute('href', '/1/settings/devices');
  await expect(nav.getByRole('link', { name: 'Général', exact: true })).toHaveCount(0);
  expect(state.writes).toHaveLength(0);
});
test('device inventory rejects unrelated order-only roles at the route boundary', async ({ page }) => {
  const state = await install(page, { permissions: ['orders.view'] }); await page.goto('/1/settings/devices'); await expect(page.getByRole('heading', { name: "Vous n'avez pas accès à cette section", exact: true })).toBeVisible(); expect(state.control.reads).toBe(0); expect(state.writes).toHaveLength(0);
});
