import { test, expect, type Page } from '@playwright/test';
import { createFixture } from './fixtures.mjs';
import type { Discount } from '../../src/lib/api';
const sample = (id = 1): Discount => ({ id, restaurant_id: 1, code: id === 1 ? 'BIENVENUE10' : 'LIVRAISON', name: 'Une attention pour les habitués — צוות המסעדה', description: 'Offre de démonstration, sans données clients.', type: id === 1 ? 'percent' : 'free_delivery', value: id === 1 ? 10 : 0, scope: id === 1 ? 'category' : 'whole_sale', scope_ids: id === 1 ? [1, 99] : [], min_purchase: 0, starts_at: null, ends_at: '2026-10-04', total_cap: id === 1 ? 0 : null, per_customer_cap: null, is_active: true, redemption_count: 0, created_at: '2026-10-01T08:00:00Z' });
async function install(page: Page, options: { locale?: string; readOnly?: boolean; currency?: string; timezone?: string } = {}) {
  const fixture = createFixture(), writes: { method: string; body: any; path: string; rid: string | undefined; query: string | null }[] = [];
  const control = { rows: [sample(), sample(2)] as Discount[], reads: 0, failRead: false, failCategory: false, failWrite: false, applyAndFail: false, malformed: false, malformedAck: false, gate: null as Promise<void> | null };
  await page.clock.setFixedTime(new Date('2026-10-04T18:00:00Z'));
  await page.addInitScript(({ locale }) => { localStorage.setItem('foody_restaurant_token', 'isolated-ui-fixture'); localStorage.setItem('foody_restaurant_user', JSON.stringify({ id: 1, full_name: 'Équipe démo', role: 'owner', email: 'demo@foody.test' })); localStorage.setItem('foody_restaurant_ids', '[1,2]'); localStorage.setItem('foody-admin-locale', locale); localStorage.setItem('foody_admin_theme', locale === 'he' ? 'dark' : 'light'); }, { locale: options.locale ?? 'fr' });
  await page.route('**/api/v1/**', async route => {
    const request = route.request(), url = new URL(request.url()), path = url.pathname, method = request.method(), body = request.postDataJSON() ?? {}, rid = request.headers()['x-restaurant-id'];
    if (path === '/api/v1/users/me') return route.fulfill({ json: { permissions: options.readOnly ? ['discounts.view'] : ['discounts.view', 'discounts.edit'], role_name: options.readOnly ? 'Viewer' : 'Owner', user: { id: 1, full_name: 'Équipe démo', role: options.readOnly ? 'staff' : 'owner' } } });
    if (path.startsWith('/api/v1/discounts')) {
      const id = Number(path.split('/')[4]);
      if (method === 'GET') { control.reads++; if (control.failRead) return route.fulfill({ status: 503, json: { error: 'Synthetic read failure' } }); if (control.malformed) return route.fulfill({ json: { unrelated: [] } }); const rows = control.rows.map(row => ({ ...row, restaurant_id: Number(rid) })); return route.fulfill({ json: id ? { discount: rows.find(row => row.id === id) } : { discounts: rows } }); }
      writes.push({ method, body, path, rid, query: url.searchParams.get('restaurant_id') }); if (control.gate) await control.gate;
      let row: Discount | undefined;
      if (!control.failWrite || control.applyAndFail) {
        if (method === 'DELETE') control.rows = control.rows.filter(row => row.id !== id);
        else if (method === 'PUT') { row = control.rows.find(row => row.id === id); if (row) Object.assign(row, body); }
        else { row = { ...sample(3), ...body, id: 3, restaurant_id: Number(rid) }; control.rows.push(row!); }
      }
      if (control.failWrite) return route.fulfill({ status: 503, json: { error: 'Synthetic uncertain write' } });
      return route.fulfill({ json: method === 'DELETE' ? {} : { discount: control.malformedAck ? { id: row?.id, restaurant_id: Number(rid), code: row?.code } : { ...row, restaurant_id: Number(rid) } } });
    }
    if (path === '/api/v1/menu/item-categories' && control.failCategory) return route.fulfill({ status: 503, json: { error: 'Synthetic catalog failure' } });
    const result = fixture.response(request.url(), method, body, Number(rid) || 1);
    if (/^\/api\/v1\/restaurants\/[12]$/.test(path) && method === 'GET' && result.json && 'restaurant' in result.json && result.json.restaurant) { Object.assign(result.json.restaurant, { timezone: options.timezone ?? 'Asia/Jerusalem', currency: options.currency ?? 'ILS' }); }
    return route.fulfill({ json: result.json ?? {}, status: result.status ?? 200 });
  });
  await page.route('**/*', route => ['localhost', '127.0.0.1'].includes(new URL(route.request().url()).hostname) ? route.fallback() : route.abort());
  return { control, writes, fixture };
}
const editor = (page: Page) => page.getByRole('dialog');
const save = (page: Page) => editor(page).getByRole('button', { name: 'Enregistrer', exact: true });
const checkSaved = (page: Page) => page.getByRole('button', { name: 'Vérifier la réduction', exact: true });
async function open(page: Page, rid = 1) { await page.goto(`/${rid}/marketing/discounts`); await page.getByRole('button', { name: 'BIENVENUE10', exact: true }).click(); }
async function rename(page: Page) { await editor(page).locator('#discount-name').fill('Nom modifié'); await save(page).click(); }
async function create(page: Page, code: string) { await page.goto('/1/marketing/discounts'); await page.getByRole('button', { name: 'Créer une réduction', exact: true }).click(); await editor(page).locator('#discount-code').fill(code); await editor(page).getByRole('combobox', { name: 'Type', exact: true }).selectOption('free_delivery'); }
async function remove(page: Page) { await page.getByRole('button', { name: 'Supprimer BIENVENUE10', exact: true }).click(); await page.getByRole('alertdialog').getByRole('button', { name: 'Supprimer', exact: true }).click(); }
for (const locale of ['fr', 'he']) test(`discounts responsive list and editor ${locale}`, async ({ page }, info) => {
  const state = await install(page, { locale }); await page.setViewportSize({ width: locale === 'fr' ? 375 : 1440, height: 1000 }); await open(page); await expect(editor(page).getByText(locale === 'fr' ? 'Référence 99' : 'הפניה 99', { exact: true })).toBeVisible(); await page.screenshot({ path: info.outputPath(`discounts-editor-${locale}.png`) }); await editor(page).locator('#discount-start').scrollIntoViewIfNeeded(); await page.screenshot({ path: info.outputPath(`discounts-conditions-${locale}.png`) }); await page.keyboard.press('Escape'); await expect(editor(page)).toHaveCount(0); await page.screenshot({ path: info.outputPath(`discounts-list-${locale}.png`) }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); expect(state.fixture.unhandled).toEqual([]);
});
test('discounts retain null start, historic zero cap, unknown selections and all fields on rename', async ({ page }) => {
  const state = await install(page); await open(page, 2); await expect(save(page)).toBeDisabled(); await expect(editor(page).locator('#discount-start')).toHaveValue(''); await expect(editor(page).locator('#discount-totalCap')).toHaveValue('0'); await rename(page); await expect(editor(page)).toHaveCount(0); const { id, restaurant_id, redemption_count, created_at, ...input } = sample(); expect(state.writes).toEqual([{ method: 'PUT', path: '/api/v1/discounts/1', rid: '2', query: '2', body: { ...input, name: 'Nom modifié' } }]);
});
test('discounts preserve each scope selection when changing scope and free-delivery type', async ({ page }) => {
  const state = await install(page); await open(page); const scope = editor(page).getByRole('combobox', { name: "S'applique à", exact: true }); await scope.selectOption('specific_item'); await editor(page).getByRole('checkbox', { name: 'Salade méditerranéenne', exact: true }).check(); await scope.selectOption('category'); await expect(editor(page).getByRole('checkbox', { name: 'Cuisine', exact: true })).toBeChecked(); await editor(page).getByRole('combobox', { name: 'Type', exact: true }).selectOption('free_delivery'); await editor(page).getByRole('combobox', { name: 'Type', exact: true }).selectOption('percent'); await expect(editor(page).getByRole('checkbox', { name: 'Référence 99', exact: true })).toBeChecked(); await scope.selectOption('specific_item'); await expect(editor(page).getByRole('checkbox', { name: 'Salade méditerranéenne', exact: true })).toBeChecked(); await save(page).click(); await expect(editor(page)).toHaveCount(0); expect(state.writes[0].body.scope_ids).toEqual([1]); expect(state.writes[0].body.scope).toBe('specific_item');
});
test('discounts validate percentages, caps and date order without a request', async ({ page }) => {
  const state = await install(page); await open(page); await editor(page).locator('#discount-value').fill('101'); await save(page).click(); await expect(editor(page).locator('#discount-value')).toBeFocused(); await expect(editor(page).getByText(/inférieur ou égal à 100/)).toBeVisible(); await editor(page).locator('#discount-value').fill('12.5'); await editor(page).locator('#discount-totalCap').fill('2.5'); await save(page).click(); await expect(editor(page).locator('#discount-totalCap')).toBeFocused(); await editor(page).locator('#discount-totalCap').fill('2'); await editor(page).locator('#discount-start').fill('2026-10-05'); await save(page).click(); await expect(editor(page).locator('#discount-end')).toBeFocused(); await expect(editor(page).getByText(/égale ou postérieure/)).toBeVisible(); expect(state.writes).toHaveLength(0);
});
test('discounts optional end date toggle preserves draft and can clear the saved bound', async ({ page }) => {
  const state = await install(page); await open(page); const toggle = editor(page).getByRole('checkbox', { name: 'Définir une date de fin', exact: true }); await toggle.uncheck(); await toggle.check(); await expect(editor(page).locator('#discount-end')).toHaveValue('2026-10-04'); await toggle.uncheck(); await save(page).click(); await expect(editor(page)).toHaveCount(0); expect(state.writes[0].body.ends_at).toBeNull();
});
test('discounts catalog retry preserves unavailable IDs and supports safe search', async ({ page }) => {
  const state = await install(page); state.control.failCategory = true; await open(page); await expect(editor(page).getByText(/Impossible de charger cette liste/)).toBeVisible(); await expect(editor(page).getByRole('checkbox', { name: 'Référence 99', exact: true })).toBeChecked(); state.control.failCategory = false; await editor(page).getByRole('button', { name: 'Réessayer', exact: true }).click(); await expect(editor(page).getByRole('checkbox', { name: 'Cuisine', exact: true })).toBeChecked(); await editor(page).getByRole('searchbox').fill('zzzz'); await expect(editor(page).getByText('Aucun résultat pour cette recherche.', { exact: true })).toBeVisible(); await rename(page); await expect(editor(page)).toHaveCount(0); expect(state.writes[0].body.scope_ids).toEqual([1, 99]);
});
test('discounts uncertain applied save reads the record without repeating PUT', async ({ page }) => {
  const state = await install(page); state.control.failWrite = true; state.control.applyAndFail = true; await open(page); await rename(page); await expect(save(page)).toBeDisabled(); await expect(editor(page).locator('#discount-name')).toHaveAttribute('readonly', ''); state.control.failRead = true; await checkSaved(page).click(); await expect(editor(page).getByText(/La vérification a échoué/)).toBeVisible(); state.control.failRead = false; await checkSaved(page).click(); await expect(editor(page)).toHaveCount(0); await expect(page.getByText('La réduction enregistrée correspond à votre saisie.', { exact: true })).toBeVisible(); expect(state.writes).toHaveLength(1);
});
test('discounts unapplied save preserves the draft and allows an explicit retry', async ({ page }) => {
  const state = await install(page); state.control.failWrite = true; await open(page); await rename(page); await checkSaved(page).click(); await expect(editor(page).getByText(/est restée inchangée/)).toBeVisible(); await expect(editor(page).locator('#discount-name')).toHaveValue('Nom modifié'); await expect(save(page)).toBeEnabled(); state.control.failWrite = false; await save(page).click(); await expect(editor(page)).toHaveCount(0); expect(state.writes).toHaveLength(2);
});
test('discounts divergent saved version is reviewed and adopted only after confirmation', async ({ page }, info) => {
  const state = await install(page); state.control.failWrite = true; await open(page); await rename(page); state.control.rows[0].description = 'Modifié par une autre session'; await checkSaved(page).click(); await editor(page).getByText('Voir les réglages enregistrés', { exact: true }).click(); await expect(editor(page).getByText('Modifié par une autre session', { exact: true })).toBeVisible(); await expect(editor(page).locator('dd').filter({ hasText: /^0$/ })).toHaveCount(1); await page.screenshot({ path: info.outputPath('discounts-recovery-fr.png') }); const adopt = editor(page).getByRole('button', { name: 'Adopter les réglages enregistrés', exact: true }); await adopt.click(); await page.getByRole('alertdialog').getByRole('button', { name: 'Annuler', exact: true }).click(); await expect(editor(page).locator('#discount-name')).toHaveValue('Nom modifié'); await adopt.click(); await page.getByRole('alertdialog').getByRole('button', { name: 'Adopter les réglages enregistrés', exact: true }).click(); await expect(editor(page).locator('#discount-name')).toHaveValue(sample().name); await expect(save(page)).toBeDisabled(); expect(state.writes).toHaveLength(1);
});
test('discounts draft leave confirmation cancels without erasing and restores trigger focus', async ({ page }) => {
  const state = await install(page); await open(page); await editor(page).locator('#discount-name').fill('Brouillon'); await page.keyboard.press('Escape'); await expect(page.getByRole('alertdialog')).toBeVisible(); await page.getByRole('alertdialog').getByRole('button', { name: 'Annuler', exact: true }).click(); await expect(editor(page).locator('#discount-name')).toHaveValue('Brouillon'); await page.keyboard.press('Escape'); await page.getByRole('alertdialog').getByRole('button', { name: 'Abandonner les modifications', exact: true }).click(); await expect(editor(page)).toHaveCount(0); await expect(page.getByRole('button', { name: 'BIENVENUE10', exact: true })).toBeFocused(); expect(state.writes).toHaveLength(0);
});
test('discounts read-only role can inspect but cannot modify or remove', async ({ page }) => {
  const state = await install(page, { readOnly: true }); await open(page); await expect(editor(page).getByText(/Votre rôle ne permet pas/)).toBeVisible(); await expect(save(page)).toHaveCount(0); await expect(editor(page).locator('#discount-name')).toHaveAttribute('readonly', ''); await expect(editor(page).getByRole('combobox', { name: 'Type', exact: true })).toBeDisabled(); await expect(editor(page).getByRole('checkbox', { name: 'Cuisine', exact: true })).toBeDisabled(); await page.keyboard.press('Escape'); await expect(page.getByRole('button', { name: 'Créer une réduction', exact: true })).toHaveCount(0); await expect(page.getByRole('button', { name: 'Supprimer BIENVENUE10', exact: true })).toHaveCount(0); expect(state.writes).toHaveLength(0);
});
test('discounts delete requires confirmation and serializes repeated clicks', async ({ page }, info) => {
  const state = await install(page); await page.goto('/2/marketing/discounts'); await page.getByRole('button', { name: 'Supprimer BIENVENUE10', exact: true }).click(); await expect(page.getByRole('alertdialog')).toHaveCSS('opacity', '1'); await page.screenshot({ path: info.outputPath('discounts-delete-fr.png'), animations: 'disabled' }); await page.getByRole('alertdialog').getByRole('button', { name: 'Annuler', exact: true }).click(); expect(state.writes).toHaveLength(0); let release!: () => void; state.control.gate = new Promise<void>(resolve => { release = resolve; }); await page.getByRole('button', { name: 'Supprimer BIENVENUE10', exact: true }).click(); await page.getByRole('alertdialog').getByRole('button', { name: 'Supprimer', exact: true }).evaluate((button: HTMLButtonElement) => { button.click(); button.click(); }); await expect(page.getByRole('button', { name: 'LIVRAISON', exact: true })).toBeDisabled(); release(); state.control.gate = null; await expect(page.getByRole('button', { name: 'BIENVENUE10', exact: true })).toHaveCount(0); expect(state.writes).toEqual([{ method: 'DELETE', body: {}, rid: '2', query: '2', path: '/api/v1/discounts/1' }]);
});
for (const applied of [true, false]) test(`discounts uncertain deletion verifies absence or presence without a second DELETE ${applied}`, async ({ page }) => {
  const state = await install(page); state.control.failWrite = true; state.control.applyAndFail = applied; await page.goto('/1/marketing/discounts'); await remove(page); const verify = page.getByRole('button', { name: 'Vérifier la suppression', exact: true }); await expect(verify).toBeVisible(); await expect(page.getByRole('button', { name: 'LIVRAISON', exact: true })).toBeDisabled(); state.control.failRead = true; await verify.click(); await expect(page.getByText(/La vérification a échoué/)).toBeVisible(); state.control.failRead = false; await verify.click(); await expect(page.getByText(applied ? 'La réduction ne figure plus dans la liste enregistrée.' : 'La réduction figure toujours dans la liste enregistrée. Vous pouvez la consulter ou demander à nouveau sa suppression.', { exact: true })).toBeVisible(); expect(state.writes).toHaveLength(1);
});
test('discounts list load failure, malformed response and empty state remain distinct', async ({ page }) => {
  const state = await install(page); state.control.failRead = true; await page.goto('/1/marketing/discounts'); await expect(page.locator('main [role=alert]')).toContainText('Impossible de charger'); await expect(page.getByText('Aucune réduction pour le moment', { exact: true })).toHaveCount(0); state.control.failRead = false; state.control.malformed = true; await page.getByRole('button', { name: 'Réessayer', exact: true }).click(); await expect(page.locator('main [role=alert]')).toContainText('Impossible de charger'); state.control.malformed = false; state.control.rows = []; await page.getByRole('button', { name: 'Réessayer', exact: true }).click(); await expect(page.getByText('Aucune réduction pour le moment', { exact: true })).toBeVisible(); expect(state.writes).toHaveLength(0);
});
test('discounts create serializes submit and preserves decimal amounts and normalized code', async ({ page }) => {
  const state = await install(page); await page.goto('/1/marketing/discounts'); await page.getByRole('button', { name: 'Créer une réduction', exact: true }).click(); await save(page).click(); await expect(editor(page).locator('#discount-code')).toBeFocused(); await editor(page).locator('#discount-code').fill('  printemps  '); await editor(page).locator('#discount-value').fill('12.75'); let release!: () => void; state.control.gate = new Promise<void>(resolve => { release = resolve; }); await save(page).evaluate((button: HTMLButtonElement) => { button.click(); button.click(); }); await expect(save(page)).toBeDisabled(); await expect(editor(page).getByRole('button', { name: 'Fermer', exact: true })).toBeDisabled(); release(); state.control.gate = null; await expect(editor(page)).toHaveCount(0); expect(state.writes).toHaveLength(1); expect(state.writes[0].body).toMatchObject({ code: 'PRINTEMPS', value: 12.75, scope: 'whole_sale', scope_ids: [], min_purchase: 0, starts_at: '2026-10-04', ends_at: null, total_cap: null, per_customer_cap: null });
});
for (const applied of [true, false]) test(`discounts uncertain creation reconciles by normalized code ${applied}`, async ({ page }) => {
  const state = await install(page); state.control.failWrite = true; state.control.applyAndFail = applied; await create(page, 'nouveau'); await save(page).click(); await checkSaved(page).click(); if (applied) { await expect(editor(page)).toHaveCount(0); await expect(page.getByRole('button', { name: 'NOUVEAU', exact: true })).toBeVisible(); } else { await expect(editor(page).getByText(/ne figure pas dans la liste enregistrée/)).toBeVisible(); await expect(save(page)).toBeEnabled(); } expect(state.writes).toHaveLength(1);
});
test('discounts uncertain duplicate creation does not overwrite an existing code', async ({ page }) => {
  const state = await install(page); state.control.failWrite = true; await create(page, 'bienvenue10'); await save(page).click(); await checkSaved(page).click(); await expect(editor(page).locator('#discount-code')).toHaveAttribute('aria-invalid', 'true'); await expect(editor(page).locator('#discount-code')).toBeFocused(); expect(state.writes).toHaveLength(1); expect(state.control.rows[0].type).toBe('percent');
});
test('discounts malformed save acknowledgement requires readback', async ({ page }) => {
  const state = await install(page); state.control.malformedAck = true; await open(page); await rename(page); await expect(checkSaved(page)).toBeVisible(); await checkSaved(page).click(); await expect(editor(page)).toHaveCount(0); expect(state.writes).toHaveLength(1);
});
test('discounts English currency, search and restaurant day are independent from browser day', async ({ page }) => {
  const state = await install(page, { locale: 'en', currency: 'EUR', timezone: 'Pacific/Honolulu' }); state.control.rows[0] = { ...sample(), type: 'fixed', value: 12.75, total_cap: null }; await page.clock.setFixedTime(new Date('2026-10-05T01:00:00Z')); await page.goto('/1/marketing/discounts'); await expect(page.getByText('€12.75', { exact: true })).toBeVisible(); await expect(page.getByText('2 active out of 2 codes', { exact: true })).toHaveCount(0); await expect(page.locator('table tbody tr').filter({ hasText: 'Active' })).toHaveCount(2); await expect(page.getByText('Oct 4, 2026', { exact: true })).toHaveCount(2); await page.getByRole('searchbox').fill('équipe introuvable'); await expect(page.getByText('No discounts match your search.', { exact: true })).toBeVisible(); await page.getByRole('searchbox').fill('bienvenue'); await expect(page.getByRole('button', { name: 'LIVRAISON', exact: true })).toHaveCount(0); expect(state.writes).toHaveLength(0);
});
test('discounts locale change preserves loaded data without another discount read', async ({ page }) => {
  const state = await install(page); await page.goto('/1/marketing/discounts'); await expect(page.getByRole('button', { name: 'BIENVENUE10', exact: true })).toBeVisible(); const reads = state.control.reads; await page.getByRole('button', { name: 'Atelier Foody', exact: true }).click(); await page.getByRole('dialog').getByRole('combobox').selectOption('he'); await page.keyboard.press('Escape'); await page.getByRole('button', { name: 'BIENVENUE10', exact: true }).click(); await expect(editor(page).getByRole('heading', { name: 'עריכת הנחה', exact: true })).toBeVisible(); await expect(editor(page).locator('#discount-totalCap')).toHaveValue('0'); expect(state.control.reads).toBe(reads); expect(state.writes).toHaveLength(0);
});
