import { test, expect, type Page } from '@playwright/test';
import { createFixture } from './fixtures.mjs';
import type { PrinterProfile } from '../../src/lib/api';
const seed = (): PrinterProfile => ({ id:'profile-1',restaurant_id:1,name:'Cuisine — production et commandes en ligne',job_types:['receipts','dine_in_tickets','online_tickets'],dine_in_category_ids:[1,99],online_category_ids:[2],auto_print_new_categories:false,one_item_per_ticket:true,print_recipient_information:false,hide_ticket_footer:true,ticket_margins:'bottom',print_kitchen_names:false,combine_identical_items:true,ticket_layout:'compact',font_size:'large',item_sort_order:'category_custom',copies:5,enabled:false,assignments:[{id:'assignment-1',device_id:'pos-1',device_name:'Caisse accueil',printer_id:'printer-1',printer_name:'Cuisine',printer_model:'Démo'},{id:'assignment-old',device_id:'old-pos',device_name:'Ancienne tablette',printer_id:'old-printer',printer_name:'Imprimante archivée',printer_model:'Démo'}],created_at:'2026-10-01T08:00:00Z',updated_at:'2026-10-04T12:00:00Z'});
async function install(page: Page, opts: {locale?:string;permissions?:string[]}={}) {
 const fixture=createFixture(), writes: {method:string;path:string;body:any;rid:string|undefined}[]=[];
 const control={profiles:[seed()],agents:[{id:'agent-1',restaurant_id:1,spooler_id:'pos-1',name:'Caisse accueil',model:'Tablette de démonstration',printer_ids:['printer-1','printer-2'] as string[]|null,last_seen_at:'2026-10-04T12:00:00Z'}],printers:[{id:'printer-1',restaurant_id:1,name:'Cuisine',model:'Démo'},{id:'printer-2',restaurant_id:1,name:'Bar',model:'Démo'},{id:'printer-3',restaurant_id:1,name:'Autre poste',model:'Démo'}],reads:0,categoryReads:0,failRead:false,malformed:false,failWrite:false,applyAndFail:false,failAfterWrite:false,gate:null as Promise<void>|null};
 await page.addInitScript(({locale})=>{localStorage.setItem('foody_restaurant_token','isolated-ui-fixture');localStorage.setItem('foody_restaurant_user',JSON.stringify({id:1,full_name:'Équipe démo',role:'manager',email:'demo@foody.test'}));localStorage.setItem('foody_restaurant_ids','[1,2]');localStorage.setItem('foody-admin-locale',locale);localStorage.setItem('foody_admin_theme',locale==='he'?'dark':'light');},{locale:opts.locale??'fr'});
 await page.route('**/api/v1/**',async route=>{
  const req=route.request(),path=new URL(req.url()).pathname,method=req.method(),body=req.postDataJSON()??{},rid=req.headers()['x-restaurant-id'];
  if(path==='/api/v1/users/me')return route.fulfill({json:{role_name:'Custom',permissions:opts.permissions??['printers.view','printers.manage'],user:{id:1,full_name:'Équipe démo',role:'manager'}}});
  if(/\/restaurants\/[12]\/printing\//.test(path)){
   if(method==='GET'){
    if(path.endsWith('/profiles')){control.reads++;return route.fulfill({status:control.failRead?503:200,json:control.failRead?{error:'Synthetic read failure'}:control.malformed?{}:{profiles:control.profiles.map(row=>({...row,restaurant_id:Number(rid)}))}});}
    if(path.endsWith('/agents'))return route.fulfill({json:{agents:control.agents.map(row=>({...row,restaurant_id:Number(rid)}))}});
    if(path.endsWith('/printers'))return route.fulfill({json:{printers:control.printers.map(row=>({...row,restaurant_id:Number(rid)}))}});
    if(path.endsWith('/spooler/categories')){control.categoryReads++;return route.fulfill({json:{categories:[{id:1,name:'Plats chauds'},{id:2,name:'Boissons'}]}});}
   }
   writes.push({method,path,body,rid});if(control.gate)await control.gate;
   let result=control.profiles.find(row=>row.id===path.split('/')[7]);
   if(!control.failWrite||control.applyAndFail){
    if(method==='DELETE') control.profiles=control.profiles.filter(row=>row.id!==result?.id);
    else if(path.endsWith('/duplicate')){result={...result!,id:`profile-${control.profiles.length+1}`,name:`${result!.name} (copy)`,assignments:[]};control.profiles.push(result);}
    else if(path.endsWith('/assignments')&&result)result.assignments=body.assignments.map((row:any,n:number)=>({...row,id:`a-${n}`,printer_name:control.printers.find(p=>p.id===row.printer_id)?.name??row.printer_id,printer_model:'Démo'}));
    else if(method==='POST'){result={...seed(),...body,id:`profile-${control.profiles.length+1}`,assignments:[]};control.profiles.push(result!);}
    else if(result)Object.assign(result,body);
   }
   if(control.failAfterWrite)control.failRead=true;
   if(control.failWrite)return route.fulfill({status:503,json:{error:'Synthetic uncertain write'}});
   if(method==='DELETE')return route.fulfill({status:204,body:''});
   return route.fulfill({json:{profile:{...result,restaurant_id:Number(rid)}}});
  }
  const result=fixture.response(req.url(),method,body,Number(rid)||1);return route.fulfill({status:result.status??200,json:result.json??{}});
 });
 await page.route('**/*',route=>['localhost','127.0.0.1'].includes(new URL(route.request().url()).hostname)?route.fallback():route.abort());
 return {control,writes,fixture};
}
const dialog=(page:Page)=>page.getByRole('dialog');
const save=(page:Page)=>dialog(page).getByRole('button',{name:/^Enregistrer$|^Enregistrement/});
const verify=(page:Page)=>page.getByRole('button',{name:'Vérifier les profils enregistrés',exact:true});
async function open(page:Page,rid=1){await page.goto(`/${rid}/settings/printers`);await expect(page.getByRole('button',{name:seed().name,exact:true})).toBeVisible();}
async function action(page:Page,name:string){await page.getByRole('button',{name:`Actions · ${seed().name}`,exact:true}).click();await page.getByRole('menuitem',{name,exact:true}).click();}
async function edit(page:Page){await action(page,'Modifier le profil');}
for(const locale of ['fr','he'])test(`printer profiles responsive list, editor and settings ${locale}`,async({page},info)=>{
 const state=await install(page,{locale});await page.setViewportSize({width:locale==='fr'?375:1440,height:1000});await open(page);await page.screenshot({path:info.outputPath(`printer-profiles-list-${locale}.png`)});await page.getByRole('button',{name:seed().name,exact:true}).click();await expect(dialog(page)).toHaveCSS('transform','none');await page.screenshot({path:info.outputPath(`printer-profiles-detail-${locale}.png`),animations:'disabled'});await dialog(page).getByRole('button',{name:locale==='fr'?'Modifier':'ערוך',exact:true}).click();await expect(dialog(page)).toHaveCSS('opacity','1');await page.screenshot({path:info.outputPath(`printer-profiles-editor-${locale}.png`),animations:'disabled'});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(state.fixture.unhandled).toEqual([]);expect(state.control.categoryReads).toBeGreaterThan(0);
});
test('printer roles load categories without a menu permission and readonly details expose all settings',async({page})=>{const state=await install(page,{permissions:['printers.view']});await open(page);await expect(page.getByRole('button',{name:'Créer un profil',exact:true})).toHaveCount(0);await page.getByRole('button',{name:seed().name,exact:true}).click();await expect(dialog(page).getByText('Réglages d’impression communs',{exact:true})).toBeVisible();await expect(dialog(page).getByRole('button',{name:'Modifier',exact:true})).toHaveCount(0);expect(state.writes).toHaveLength(0);expect(state.control.categoryReads).toBeGreaterThan(0);expect(state.fixture.unhandled).toEqual([]);});
test('printer search includes assignment names and handles no matches',async({page})=>{await install(page);await open(page);await page.getByRole('searchbox').fill('Ancienne tablette');await expect(page.getByRole('button',{name:seed().name,exact:true})).toBeVisible();await page.getByRole('searchbox').fill('ZZZ');await expect(page.getByText('Aucun profil ne correspond à cette recherche.',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Réinitialiser',exact:true}).click();await expect(page.getByRole('button',{name:seed().name,exact:true})).toBeVisible();});
test('printer failed and malformed load is distinct from empty and retries',async({page})=>{const state=await install(page);state.control.failRead=true;await page.goto('/1/settings/printers');await expect(page.getByRole('alert').filter({hasText:'Impossible de charger'})).toBeVisible();await expect(page.getByText('Aucun profil d’imprimante',{exact:true})).toHaveCount(0);state.control.failRead=false;state.control.malformed=true;await page.getByRole('button',{name:'Réessayer',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'Impossible de charger'})).toBeVisible();state.control.malformed=false;state.control.profiles=[];await page.getByRole('button',{name:'Réessayer',exact:true}).click();await expect(page.getByText('Aucun profil d’imprimante',{exact:true})).toBeVisible();});
test('printer create uses exact defaults, scoped request and synchronous double-submit guard',async({page})=>{const state=await install(page);await open(page,2);await page.getByRole('button',{name:'Créer un profil',exact:true}).click();await expect(save(page)).toBeDisabled();await dialog(page).getByRole('textbox',{name:'Nom du profil',exact:true}).fill('  Reçus démo  ');await dialog(page).getByRole('switch',{name:'Reçus',exact:true}).check();let release!:()=>void;state.control.gate=new Promise<void>(resolve=>{release=resolve;});await save(page).evaluate((el:HTMLButtonElement)=>{el.click();el.click();});await expect(save(page)).toBeDisabled();await expect(dialog(page).getByRole('button',{name:'Fermer',exact:true})).toBeDisabled();await expect(dialog(page).getByRole('textbox')).toBeDisabled();release();state.control.gate=null;await expect(dialog(page)).toHaveCount(0);expect(state.writes).toHaveLength(1);expect(state.writes[0]).toMatchObject({method:'POST',path:'/api/v1/restaurants/2/printing/profiles',rid:'2',body:{name:'Reçus démo',job_types:['receipts'],dine_in_category_ids:[1,2],online_category_ids:[1,2],copies:1,enabled:true,ticket_margins:'both',print_recipient_information:true,hide_ticket_footer:true}});expect(state.writes[0].body.id).toBeUndefined();});
test('printer editor retains hidden categories and formatting while avoiding duplicated shared controls',async({page},info)=>{const state=await install(page);await open(page);await edit(page);await expect(dialog(page).getByRole('checkbox',{name:'Imprimer les informations du destinataire',exact:true})).toHaveCount(1);await dialog(page).getByRole('switch',{name:'Tickets en ligne',exact:true}).uncheck();await dialog(page).getByRole('switch',{name:'Tickets sur place',exact:true}).uncheck();await dialog(page).getByRole('textbox',{name:'Nom du profil',exact:true}).fill('Reçus modifiés');await save(page).click();await expect(dialog(page)).toHaveCount(0);expect(state.writes[0].body).toMatchObject({job_types:['receipts'],dine_in_category_ids:[1,99],online_category_ids:[2],copies:5,ticket_layout:'compact',font_size:'large',enabled:false,auto_print_new_categories:false,one_item_per_ticket:true});await page.getByRole('button',{name:'Actions · Reçus modifiés',exact:true}).click();await page.getByRole('menuitem',{name:'Modifier le profil',exact:true}).click();await dialog(page).getByRole('switch',{name:'Tickets sur place',exact:true}).check();await dialog(page).getByRole('combobox',{name:'Marges des tickets',exact:true}).selectOption('none');await dialog(page).getByRole('combobox',{name:'Ordre de tri des articles',exact:true}).selectOption('seat');await dialog(page).getByRole('combobox',{name:'Taille de la police',exact:true}).selectOption('small');await dialog(page).getByRole('combobox',{name:'Mise en page des tickets',exact:true}).selectOption('classic');await dialog(page).getByRole('button',{name:'Diminuer',exact:true}).click();await page.screenshot({path:info.outputPath('printer-profiles-format-fr.png')});await save(page).click();await expect(dialog(page)).toHaveCount(0);expect(state.writes[1].body).toMatchObject({ticket_margins:'none',item_sort_order:'seat',font_size:'small',ticket_layout:'classic',copies:4});});
test('printer UTF-8 name limit and duplicate name never send invalid writes',async({page})=>{const state=await install(page);await open(page);await edit(page);await dialog(page).getByRole('textbox',{name:'Nom du profil',exact:true}).fill('א'.repeat(61));await save(page).click();await expect(dialog(page).getByText(/120 octets UTF-8/)).toBeVisible();expect(state.writes).toHaveLength(0);await dialog(page).getByRole('textbox',{name:'Nom du profil',exact:true}).fill('א'.repeat(60));await save(page).click();await expect(dialog(page)).toHaveCount(0);expect(state.writes).toHaveLength(1);await page.getByRole('button',{name:'Créer un profil',exact:true}).click();await dialog(page).getByRole('textbox',{name:'Nom du profil',exact:true}).fill('א'.repeat(60));await dialog(page).getByRole('switch',{name:'Reçus',exact:true}).check();await save(page).click();await expect(dialog(page).getByText('Un profil utilise déjà ce nom. Choisissez un autre nom.',{exact:true})).toBeVisible();expect(state.writes).toHaveLength(1);});
test('printer drafts guard close and transition to assignment editing',async({page})=>{const state=await install(page);await open(page);await edit(page);await dialog(page).getByRole('textbox',{name:'Nom du profil',exact:true}).fill('Brouillon');await dialog(page).getByRole('button',{name:'Fermer',exact:true}).click();await expect(page.getByRole('alertdialog')).toBeVisible();await page.getByRole('alertdialog').getByRole('button',{name:'Annuler',exact:true}).click();await expect(dialog(page).getByRole('textbox')).toHaveValue('Brouillon');await dialog(page).getByRole('button',{name:'Attribuer des imprimantes',exact:true}).click();await page.getByRole('alertdialog').getByRole('button',{name:'Abandonner les modifications',exact:true}).click();await expect(dialog(page).getByRole('combobox')).toBeVisible();await expect(save(page)).toBeDisabled();expect(state.writes).toHaveLength(0);});
test('printer selecting all categories preserves unavailable IDs until explicit removal',async({page})=>{const state=await install(page);await open(page);await edit(page);const region=dialog(page).getByRole('region',{name:'Tickets sur place',exact:true});await region.locator('summary').click();await expect(region.getByRole('checkbox',{name:'Catégorie indisponible · 99',exact:true})).toBeChecked();await region.getByRole('checkbox',{name:'Tout sélectionner',exact:true}).check();await save(page).click();await expect(dialog(page)).toHaveCount(0);expect(state.writes[0].body.dine_in_category_ids).toEqual([1,99,2]);});
test('printer assignments preserve unavailable devices and restrict options to observed printers',async({page},info)=>{const state=await install(page);await open(page);await action(page,'Modifier les imprimantes assignées');await expect(dialog(page).getByRole('option',{name:/Autre poste/})).toHaveCount(0);await dialog(page).getByRole('combobox').selectOption('printer-2');await expect(dialog(page)).toHaveCSS('opacity','1');await page.screenshot({path:info.outputPath('printer-profiles-assignments-fr.png'),animations:'disabled'});await save(page).click();await expect(dialog(page)).toHaveCount(0);expect(state.writes[0].body.assignments).toEqual([{device_id:'pos-1',device_name:'Caisse accueil',printer_id:'printer-2'},{device_id:'old-pos',device_name:'Ancienne tablette',printer_id:'old-printer'}]);await action(page,'Modifier les imprimantes assignées');await dialog(page).getByRole('button',{name:'Retirer cette affectation',exact:true}).click();await save(page).click();await expect(dialog(page)).toHaveCount(0);expect(state.writes[1].body.assignments).toHaveLength(1);});
test('printer unavailable assignment is represented when Go returns null observations',async({page})=>{const state=await install(page);state.control.agents[0].printer_ids=null;await open(page);await action(page,'Modifier les imprimantes assignées');await expect(dialog(page).getByRole('combobox')).toHaveValue('printer-1');await expect(dialog(page).getByRole('option',{name:'Indisponible · Cuisine',exact:true})).toHaveCount(1);await dialog(page).getByRole('button',{name:'Retirer cette affectation',exact:true}).click();await save(page).click();await expect(dialog(page)).toHaveCount(0);expect(state.writes[0].body.assignments).toEqual([{device_id:'pos-1',device_name:'Caisse accueil',printer_id:'printer-1'}]);});
for(const kind of ['create','update','assign','duplicate','delete'])test(`printer uncertain ${kind} reconciles through GET without repeating writes`,async({page})=>{const state=await install(page);state.control.failWrite=true;state.control.applyAndFail=true;state.control.failAfterWrite=true;await open(page);const reads=state.control.reads;if(kind==='create'){await page.getByRole('button',{name:'Créer un profil',exact:true}).click();await dialog(page).getByRole('textbox',{name:'Nom du profil',exact:true}).fill('Nouveau profil');await dialog(page).getByRole('switch',{name:'Reçus',exact:true}).check();await save(page).click();}else if(kind==='update'){await edit(page);await dialog(page).getByRole('textbox',{name:'Nom du profil',exact:true}).fill('Cuisine modifiée');await save(page).click();}else if(kind==='assign'){await action(page,'Modifier les imprimantes assignées');await dialog(page).getByRole('combobox').selectOption('printer-2');await save(page).click();}else if(kind==='duplicate'){await action(page,'Dupliquer le profil');}else{await action(page,'Supprimer le profil');await page.getByRole('alertdialog').getByRole('button',{name:'Supprimer',exact:true}).click();}await expect(verify(page)).toBeVisible();if(['create','update','assign'].includes(kind)){await expect(save(page)).toBeDisabled();await expect(dialog(page).getByRole('button',{name:'Fermer',exact:true})).toBeDisabled();}await verify(page).click();await expect(page.getByText(/Impossible de vérifier les profils enregistrés/)).toBeVisible();state.control.failRead=false;await verify(page).click();await expect(verify(page)).toHaveCount(0);await expect(dialog(page)).toHaveCount(0);expect(state.writes).toHaveLength(1);expect(state.control.reads).toBe(reads+2);});
test('printer differing saved state preserves draft and needs confirmation to adopt',async({page},info)=>{const state=await install(page);state.control.failWrite=true;await open(page);await edit(page);await dialog(page).getByRole('textbox',{name:'Nom du profil',exact:true}).fill('Brouillon conservé');await save(page).click();await verify(page).click();await expect(dialog(page).getByRole('textbox')).toHaveValue('Brouillon conservé');await dialog(page).getByText('Voir la version enregistrée',{exact:true}).click();await page.screenshot({path:info.outputPath('printer-profiles-recovery-fr.png')});await dialog(page).getByRole('button',{name:'Utiliser la version enregistrée',exact:true}).click();await page.getByRole('alertdialog').getByRole('button',{name:'Annuler',exact:true}).click();await expect(dialog(page).getByRole('textbox')).toHaveValue('Brouillon conservé');await dialog(page).getByRole('button',{name:'Utiliser la version enregistrée',exact:true}).click();await page.getByRole('alertdialog').getByRole('button',{name:'Utiliser la version enregistrée',exact:true}).click();await expect(dialog(page).getByRole('textbox')).toHaveValue(seed().name);await expect(save(page)).toBeDisabled();expect(state.writes).toHaveLength(1);});
test('printer duplication never copies assignments and confirmed delete removes only the profile',async({page},info)=>{const state=await install(page);await open(page);await action(page,'Dupliquer le profil');await expect(page.getByRole('button',{name:`${seed().name} (copy)`,exact:true})).toBeVisible();expect(state.control.profiles[1].assignments).toEqual([]);await action(page,'Supprimer le profil');await expect(page.getByRole('alertdialog')).toHaveCSS('opacity','1');await page.screenshot({path:info.outputPath('printer-profiles-delete-fr.png'),animations:'disabled'});await page.getByRole('alertdialog').getByRole('button',{name:'Annuler',exact:true}).click();expect(state.writes).toHaveLength(1);await action(page,'Supprimer le profil');await page.getByRole('alertdialog').getByRole('button',{name:'Supprimer',exact:true}).click();await expect(page.getByRole('button',{name:seed().name,exact:true})).toHaveCount(0);expect(state.control.printers).toHaveLength(3);expect(state.writes).toHaveLength(2);});
test('printer locale switch retains data without refetching',async({page})=>{const state=await install(page);await open(page);const reads=state.control.reads;await page.getByRole('button',{name:'Foody · Profil',exact:true}).click();await dialog(page).getByRole('button',{name:'עברית',exact:true}).click();await page.keyboard.press('Escape');await expect(page.getByRole('heading',{name:'פרופילי מדפסות',exact:true})).toBeVisible();expect(state.control.reads).toBe(reads);});
test('printer English empty workspace remains accessible on mobile',async({page})=>{const state=await install(page,{locale:'en'});state.control.profiles=[];await page.setViewportSize({width:375,height:812});await page.goto('/2/settings/printers');await expect(page.getByRole('button',{name:'Create profile',exact:true})).toBeVisible();await expect(page.getByText('No printer profiles',{exact:true})).toBeVisible();expect(state.writes).toHaveLength(0);});
test('printer assignment draft guards dismissal and restores an explicitly removed missing device',async({page})=>{const state=await install(page);await open(page);await action(page,'Modifier les imprimantes assignées');await dialog(page).getByRole('button',{name:'Retirer cette affectation',exact:true}).click();await dialog(page).getByRole('button',{name:'Fermer',exact:true}).click();await page.getByRole('alertdialog').getByRole('button',{name:'Annuler',exact:true}).click();await dialog(page).getByRole('button',{name:'Conserver cette affectation',exact:true}).click();await expect(save(page)).toBeDisabled();await dialog(page).getByRole('button',{name:'Fermer',exact:true}).click();await expect(dialog(page)).toHaveCount(0);expect(state.writes).toHaveLength(0);});
test('printer absent uncertain create retains draft before an explicit second save',async({page})=>{const state=await install(page);state.control.failWrite=true;await open(page);await page.getByRole('button',{name:'Créer un profil',exact:true}).click();await dialog(page).getByRole('textbox',{name:'Nom du profil',exact:true}).fill('Profil non créé');await dialog(page).getByRole('switch',{name:'Reçus',exact:true}).check();await save(page).click();await verify(page).click();await expect(dialog(page).getByText(/Aucun profil enregistré ne porte ce nom/)).toBeVisible();expect(state.writes).toHaveLength(1);state.control.failWrite=false;await save(page).click();await expect(dialog(page)).toHaveCount(0);expect(state.writes).toHaveLength(2);expect(state.writes.every(row=>row.method==='POST')).toBe(true);});
test('printer uncertain delete that did not apply keeps the profile for review',async({page})=>{const state=await install(page);state.control.failWrite=true;await open(page);await action(page,'Supprimer le profil');await page.getByRole('alertdialog').getByRole('button',{name:'Supprimer',exact:true}).click();await verify(page).click();await expect(dialog(page).getByText(/Le profil est toujours enregistré/)).toBeVisible();expect(state.control.profiles).toHaveLength(1);expect(state.writes).toHaveLength(1);await dialog(page).getByRole('button',{name:'Fermer',exact:true}).click();await expect(page.getByRole('button',{name:seed().name,exact:true})).toBeVisible();});
test('printer uncertain duplicate with no identifiable copy requests list review without another POST',async({page})=>{const state=await install(page);state.control.failWrite=true;await open(page);await action(page,'Dupliquer le profil');await verify(page).click();await expect(page.getByText(/La copie n’a pas pu être identifiée avec certitude/)).toBeVisible();expect(state.writes).toHaveLength(1);expect(state.control.profiles).toHaveLength(1);});
